-- Naxxramas (WotLK, 10/25)
-- Boss fields: name, aliases, tldr, start, general, tank, heal, dps, abilities, hard, src
-- Line tags:  "[10] text" only in 10-man, "[25] text" only in 25-man, "#{a/b}" = a in 10-man / b in 25-man.
-- Ability: { id/ids = spell ID(s) (only linked if the client confirms the name), name, desc }
-- Timers below match the AzerothCore scripts that ChromieCraft runs.
local WM = WrathMentor

WM:AddRaid("naxx", "Naxxramas", { "Naxxramas" }, {
    ------------------------------------------------------------------ ARACHNID QUARTER
    {
        name = "Anub'Rekhan",
        npcId = 15956,
        tldr = "Kill every Crypt Guard, stay spread for Impale, and stay 30+ yards away from him during Locust Swarm while the tank kites him. AoE the Corpse Scarabs.",
        start = {
            "[10] One Crypt Guard joins about 17 seconds after the pull. An off-tank picks it up.",
            "[25] Two Crypt Guards are already up at the pull - the off-tank grabs both.",
            "Main tank turns Anub'Rekhan away from the raid. Ranged and healers spread out BEFORE the pull so one Impale can't hit several people.",
        },
        general = {
            "## Locust Swarm (every 90 seconds, lasts about 20 seconds)",
            "He gets a 30-yard aura that damages and silences. The main tank kites him slowly along the outer wall; everyone else keeps 30+ yards away the whole time.",
            "A new Crypt Guard spawns with every Locust Swarm. The off-tank picks it up and DPS kill it.",
            "## Between swarms",
            "Impale (every 20 seconds) throws a random player into the air and hits everyone in a line between him and the target - stay spread so it hits one person.",
            "Every dead Crypt Guard (and every dead player) releases Corpse Scarabs: AoE them down at once.",
        },
        tank = {
            "Main tank: face him away from the raid. When Locust Swarm starts, walk him along the outer wall and keep moving until it ends - a speed effect (Aspect of the Pack, Sprint, speed potion) helps. Don't drag him through the raid.",
            "Off-tank: hold each Crypt Guard away from the raid (they Cleave and spit acid) and pick up the Corpse Scarabs when a Guard dies so they don't run at healers.",
        },
        heal = {
            "Stay spread and at least 30 yards from Anub'Rekhan during Locust Swarm, or you get silenced.",
            "The kiting tank takes swarm damage while moving away from you: pre-HoT/shield before the swarm and use instant heals while he walks.",
            "Top off whoever was hit by Impale - they also take fall damage.",
        },
        dps = {
            "Kill order: Crypt Guard > Corpse Scarabs (AoE) > Anub'Rekhan.",
            "Stay spread (Impale) and keep 30 yards from him during Locust Swarm. Melee: stop and back off when the swarm starts instead of chasing him.",
            "Frost Nova, Frost Trap and other slows help pin the Scarabs for AoE.",
        },
        abilities = {
            { ids = { 28785, 54021 }, name = "Locust Swarm", desc = "Every 90 seconds: a 30-yard aura that damages and silences for about 20 seconds. The tank kites him; everyone else stays away. A new Crypt Guard spawns each time." },
            { ids = { 28783, 56090 }, name = "Impale", desc = "Every 20 seconds on a random player: damage and a knock-up, also hitting anyone in the line between him and the target. Spread out." },
        },
    },
    {
        name = "Grand Widow Faerlina",
        npcId = 15953,
        tldr = "Step out of Rain of Fire, dispel the poison, and remove her Frenzy with Widow's Embrace: in 25-man a Priest Mind Controls a Worshipper to cast it; in 10-man you kill a Worshipper right next to her.",
        start = {
            "Main tank holds Faerlina. The off-tank picks up the 4 Worshippers and keeps them near her but out of the raid.",
            "[25] A second off-tank takes the 2 Naxxramas Followers and keeps them away from casters. One or two Priests are assigned to Mind Control.",
            "[10] Pick one Worshipper as the 'Embrace' target and bring it low (around 10%) before her first Frenzy.",
        },
        general = {
            "## Frenzy and Widow's Embrace",
            "About 60-80 seconds in, and then every minute, she Frenzies: much faster and harder hits on the tank.",
            "Widow's Embrace on Faerlina removes Frenzy, stops Poison Bolt Volley for 30 seconds and pushes her next Frenzy back a full minute.",
            "[25] The Priest Mind Controls a Worshipper, walks it next to Faerlina and uses its Widow's Embrace. The Worshipper dies after casting it.",
            "[10] Kill the pre-weakened Worshipper while it stands next to Faerlina - it casts Widow's Embrace on her as it dies.",
            "Use it as soon as she Frenzies. You have 4 Worshippers, so 4 Embraces in total.",
            "## Everything else",
            "Rain of Fire: a fire patch under a random player - step out.",
            "Poison Bolt Volley: nature damage plus a poison on several players - dispel it (Cleansing Totem helps).",
            "[25] Followers silence everyone within 10 yards and charge random players - kill them early.",
        },
        tank = {
            "Main tank: face Faerlina away from the raid and use a cooldown if Frenzy is up for more than a few seconds.",
            "Off-tank: hold all 4 Worshippers within about 15 yards of Faerlina (they must be close for the Embrace) but away from AoE - don't let DPS cleave them.",
            "[25] Second off-tank: keep the Followers away from healers and casters (their Silence has a 10-yard range).",
        },
        heal = {
            "Dispel Poison Bolt Volley; the poison keeps ticking for 8 seconds.",
            "Frenzy hits the tank very hard - if the Embrace is late, use tank cooldowns (Pain Suppression, Guardian Spirit, Hand of Sacrifice).",
            "[25] Priests on Mind Control: watch for the Frenzy emote, Mind Control a Worshipper right away, walk it to her and press Widow's Embrace.",
            "Stay out of Rain of Fire.",
            "[25] Stay 10+ yards from the Followers (Silence).",
        },
        dps = {
            "Attack Faerlina. Never AoE near the Worshippers - they're needed for the Embrace.",
            "[25] Kill the 2 Followers first.",
            "[10] When she Frenzies, kill the pre-weakened Worshipper while it's next to her.",
            "Move out of Rain of Fire immediately.",
        },
        abilities = {
            { ids = { 28796, 54098 }, name = "Poison Bolt Volley", desc = "Nature damage and an 8-second poison on several players. Dispel it. Not cast while Widow's Embrace is on her." },
            { ids = { 28794, 54099 }, name = "Rain of Fire", desc = "Fire on the ground under a random player. Step out of it immediately." },
            { kind = "buff", ids = { 28798, 54100 }, name = "Frenzy", desc = "About every minute: she attacks much faster and harder. Removed by Widow's Embrace." },
            { ids = { 28732, 54097 }, name = "Widow's Embrace", desc = "Cast on her by a Worshipper (Mind Controlled in 25-man, killed next to her in 10-man): removes Frenzy, stops Poison Bolt Volley for 30 seconds and delays the next Frenzy by a minute." },
        },
    },
    {
        name = "Maexxna",
        npcId = 15952,
        tldr = "Free the players stuck in Web Wraps, HoT everyone before every Web Spray (every 40 seconds), dispel Necrotic Poison off the tank, AoE the Spiderlings, and burn her when she Frenzies at 30%.",
        start = {
            "Tank Maexxna away from the walls the raid uses and turn her away from everyone (Poison Shock is a frontal cone).",
            "Assign ranged DPS to the web cocoons on the walls.",
            "Healers put HoTs and shields on the tank early: the first Web Spray comes 40 seconds after the pull.",
        },
        general = {
            "## Web Wrap (20 seconds in, then every 40 seconds)",
            "#{One player is/Two players are} pulled to the wall and wrapped. Destroy the cocoon to free them.",
            "## Web Spray (every 40 seconds)",
            "Stuns the whole raid for 6 seconds and deals nature damage. Nobody can heal during the stun, so HoTs and shields must already be on the tank.",
            "## The rest",
            "Necrotic Poison on the tank cuts healing taken by 90% for 30 seconds - dispel it at once.",
            "Spiderlings spawn around her every 40 seconds: AoE them before they reach healers.",
            "At 30% she Frenzies (50% faster attacks, 75% more damage): use cooldowns and Bloodlust/Heroism and finish her.",
        },
        tank = {
            "Keep her facing away from the raid so Poison Shock only hits you.",
            "She keeps hitting you during the 6-second Web Spray stun: be topped off before it and use a defensive cooldown at 30% when she Frenzies.",
            "Call for a poison dispel if Necrotic Poison stays on you.",
        },
        heal = {
            "Dispel Necrotic Poison from the tank immediately - it reduces healing taken by 90%.",
            "Roll HoTs/shields on the tank and top the raid off a few seconds before every Web Spray (40-second timer). Nothing can be cast during the 6-second stun.",
            "At 30% the tank damage spikes - save cooldowns for that.",
        },
        dps = {
            "Ranged: break the Web Wrap cocoon first, then return to Maexxna.",
            "AoE the Spiderlings as soon as they appear.",
            "Don't start long casts right before Web Spray. Save Bloodlust/Heroism and cooldowns for 30%.",
        },
        abilities = {
            { kind = "debuff", id = 28622, name = "Web Wrap", desc = "Every 40 seconds: #{1 player is/2 players are} wrapped on the wall. Destroy the cocoon to free them." },
            { ids = { 29484, 54125 }, name = "Web Spray", desc = "Every 40 seconds: stuns the whole raid for 6 seconds with nature damage. Heal up before it." },
            { kind = "debuff", ids = { 28776, 54121 }, name = "Necrotic Poison", desc = "On the tank: -90% healing taken for 30 seconds. Dispel it quickly." },
            { ids = { 28741, 54122 }, name = "Poison Shock", desc = "Nature damage in a cone in front of her. Keep her facing away from the raid." },
            { kind = "buff", ids = { 54123, 54124 }, name = "Frenzy", desc = "At 30%: 50% faster attacks and 75% more damage. Burn her." },
        },
    },
    ------------------------------------------------------------------ PLAGUE QUARTER
    {
        name = "Noth the Plaguebringer",
        npcId = 15954,
        tldr = "Decurse Curse of the Plaguebringer immediately (#{3/10} players), kill the Plagued Warriors, and kill the skeleton waves while he's on his balcony. #{/In 25-man, re-taunt after every Blink.}",
        start = {
            "Tank Noth where the raid can collapse on him; an off-tank waits for the Plagued Warriors.",
            "Assign decursers (Mage, Druid, Shaman Cleanse Spirit): Curse of the Plaguebringer must be removed within seconds.",
        },
        general = {
            "## Ground phase (about 110 seconds)",
            "Curse of the Plaguebringer (every 25 seconds) hits #{3/10} players. If it isn't removed, it becomes Wrath of the Plaguebringer - heavy damage to the cursed player and everyone around them.",
            "#{2/3} Plagued Warriors spawn every 30 seconds: the off-tank picks them up and DPS kill them.",
            "[25] Blink (every 30 seconds): Noth casts Cripple on players near him and teleports, dropping all threat. DPS stop until the tank has him again.",
            "## Balcony phase (70 seconds)",
            "Noth teleports to his balcony and can't be attacked. A wave of skeletons spawns every 30 seconds:",
            "1st balcony: #{2/4} Plagued Champions per wave. 2nd: #{1/2} Champions + #{1/2} Plagued Guardians. 3rd: #{2/4} Guardians.",
            "Champions use Mortal Strike and Shadow Shock; Guardians cast Arcane Explosion - kill them fast.",
            "After 70 seconds he returns and the ground phase repeats. He Berserks after the 3rd balcony, so DPS must be on him every ground phase.",
        },
        tank = {
            "Main tank: hold Noth.",
            "[25] After each Blink he resets threat and appears elsewhere - taunt him right away and pull him back.",
            "Off-tank: pick up every Plagued Warrior, and on the balcony, every Champion/Guardian, and keep them stacked for AoE.",
        },
        heal = {
            "Decurse Curse of the Plaguebringer the moment it lands - this is the wipe mechanic.",
            "[25] Cleanse Cripple after Blink (it slows and lowers strength).",
            "Champions' Shadow Shock hits everyone around them - keep the melee and off-tank topped during balcony waves.",
        },
        dps = {
            "Ground: kill the Plagued Warriors, then Noth.",
            "[25] Stop attacking after a Blink until the tank has threat back.",
            "Balcony: AoE the skeletons, focusing Champions and Guardians first.",
            "Mages, Druids and Shamans: help decurse.",
        },
        abilities = {
            { kind = "debuff", ids = { 29213, 54835 }, name = "Curse of the Plaguebringer", desc = "Every 25 seconds on #{3/10} players. Remove it right away or it becomes Wrath of the Plaguebringer." },
            { ids = { 29214, 54836 }, name = "Wrath of the Plaguebringer", desc = "Heavy damage to the cursed player and everyone near them when the curse isn't removed." },
            { ids = { 29208, 29209, 29210, 29211 }, name = "Blink", desc = "25-man only, every 30 seconds: Noth teleports and drops all threat." },
            { kind = "debuff", id = 29212, name = "Cripple", desc = "25-man: cast with Blink on nearby players - slows them and lowers strength. Dispel it." },
        },
    },
    {
        name = "Heigan the Unclean",
        npcId = 15936,
        tldr = "Dance through the eruptions: the room has 4 zones and only one is safe at a time - move 1-2-3-4-3-2-1... Ranged and healers stay on the platform in phase 1; EVERYONE dances in phase 2.",
        start = {
            "The floor is split into 4 strips side by side. Zone 1 is the strip where the tank and melee start; the safe zone moves one strip at a time to the far side and back.",
            "Tank and melee start in zone 1 with Heigan. Ranged and healers go up on the platform behind him (stay 30+ yards from Heigan).",
        },
        general = {
            "## Phase 1 (90 seconds) - slow dance",
            "Every 10 seconds the floor erupts everywhere except one strip. Move to the next strip in order 1-2-3-4-3-2-1-2-3... Move right after an eruption, not before.",
            "Spell Disruption slows spellcasting by 300% within 30 yards of Heigan - the reason casters stay on the platform.",
            "Decrepit Fever (disease) halves max health of melee near him - Cure Disease / Cleanse it.",
            "## Phase 2 (45 seconds) - fast dance",
            "Heigan teleports to the platform and fills it with Plague Cloud. Ranged and healers jump down at once and join zone 1.",
            "Eruptions now come every 4 seconds - keep moving one strip each time.",
            "After 45 seconds he comes back down and phase 1 restarts. There's no hard enrage; dying to Eruption is the only real danger.",
        },
        tank = {
            "Drag Heigan with you through the safe zones, keeping him faced away. Move as soon as an eruption finishes so melee can follow you.",
            "In phase 2 you dance like everyone else - pick him back up when he returns to the floor.",
        },
        heal = {
            "Phase 1: heal from the platform; the tank and melee take Decrepit Fever and melee damage. Dispel the disease.",
            "Phase 2: leave the platform immediately and dance. Use instants while moving and only heal when you're in the safe strip.",
        },
        dps = {
            "Melee: follow the tank strip by strip; never stay to finish a cast or combo.",
            "Ranged: use cooldowns on the platform in phase 1, then jump down at once when he teleports.",
            "If you're not sure of the next zone, follow someone who is.",
        },
        abilities = {
            { ids = { 29371 }, name = "Eruption", desc = "The floor erupts in every zone but one - every 10 seconds in phase 1, every 4 seconds in phase 2. Stand in the safe zone." },
            { kind = "debuff", id = 29310, name = "Spell Disruption", desc = "Slows casting by 300% within 30 yards of Heigan. Casters stay on the platform in phase 1." },
            { kind = "debuff", ids = { 29998, 55011 }, name = "Decrepit Fever", desc = "A disease that halves maximum health. Dispel it." },
            { id = 29350, name = "Plague Cloud", desc = "Phase 2: deadly cloud over the platform. Everyone leaves the platform." },
        },
    },
    {
        name = "Loatheb",
        npcId = 16011,
        tldr = "Healing only works in a 3-second window after each Necrotic Aura (every 20 seconds) - absorbs and pre-casts carry the fight. Kill a Spore near the melee for the crit buff. Inevitable Doom hits the whole raid from 2 minutes on.",
        start = {
            "Tank Loatheb in the middle of the room. The raid stays fairly close to him so Spores can be killed near the DPS.",
            "Healers agree on a rotation and on who shields/HoTs whom - you can only heal in short windows.",
            "Berserk at 12 minutes.",
        },
        general = {
            "## Necrotic Aura (every 20 seconds, lasts 17)",
            "While it's up, healing does nothing. After it fades there's a 3-second window: pre-cast so heals land the moment it drops (the boss emotes 3 seconds before).",
            "Absorbs still work during the aura: Power Word: Shield, Sacred Shield and Divine Aegis protect players while normal heals and HoT ticks do nothing.",
            "## Deathbloom (every 30 seconds)",
            "Damage over time on everyone for 6 seconds, then a burst when it ends. Have the raid healthy before it.",
            "## Spores (every 35 seconds)",
            "Kill each Spore next to your melee/ranged group. The closest players get Fungal Creep: +50% crit, but their attacks generate NO threat - so tanks stay away from Spores.",
            "## Inevitable Doom (from 2 minutes, every 30 seconds; every 15 seconds after the 6th)",
            "Hits the whole raid with a big shadow tick after 10 seconds. Time the healing windows so everyone is topped before it lands. This is the real DPS check - kill him before the 15-second Dooms stack up.",
        },
        tank = {
            "Hold Loatheb still in the middle. Stay away from Spores - Fungal Creep would stop your threat.",
            "Use defensive cooldowns while Necrotic Aura is up if your health is low; you can only be healed for 3 seconds every 20.",
        },
        heal = {
            "Watch the aura timer and start your cast so it lands right as Necrotic Aura ends. Big heals (Greater Heal, Holy Light, Chain Heal) in the window, HoTs refreshed right after it.",
            "Discipline Priests and Holy Paladins: Power Word: Shield / Sacred Shield the tank and raid during the aura - absorbs still work.",
            "Make sure the raid is topped up before each Deathbloom burst and each Inevitable Doom.",
        },
        dps = {
            "Kill the Spore when it's next to your group to get Fungal Creep (+50% crit). It removes your threat, so go all-in.",
            "Do not kill a Spore near the tank.",
            "Pure DPS race once Inevitable Doom speeds up: use Bloodlust/Heroism and cooldowns with Fungal Creep up.",
        },
        abilities = {
            { kind = "debuff", id = 55593, name = "Necrotic Aura", desc = "Every 20 seconds for 17 seconds: healing has no effect. Heal in the 3-second gap; absorbs still work." },
            { ids = { 29865, 55053 }, name = "Deathbloom", desc = "Every 30 seconds: damage over 6 seconds on the raid, then a burst when it ends." },
            { kind = "debuff", ids = { 29204, 55052 }, name = "Inevitable Doom", desc = "From 2 minutes, every 30 seconds (every 15 after the 6th): the whole raid takes a big shadow hit after 10 seconds." },
            { kind = "buff", id = 29232, name = "Fungal Creep", desc = "From killing a Spore near you: +50% critical strike chance, but your attacks generate no threat. Tanks avoid it." },
        },
    },
    ------------------------------------------------------------------ MILITARY QUARTER
    {
        name = "Instructor Razuvious",
        npcId = 16061,
        aliases = { "Death Knight Understudy" },
        tldr = "Razuvious can only be tanked by a Death Knight Understudy with Bone Barrier up. Control two Understudies (Orbs in 10-man, Priest Mind Control in 25-man) and swap Razuvious between them with Taunt.",
        start = {
            "[10] There are 2 Understudies. Two players (usually the tanks) click the Obedience Crystals next to the platform to control one each.",
            "[25] There are 4 Understudies. Two Priests Mind Control one each; the other 2 are held off to the side by real tanks (don't kill them - they're spare tanks).",
            "Understudy action bar: Blood Strike, Bone Barrier and Taunt. Controller 1 Bone Barriers and Taunts Razuvious first.",
        },
        general = {
            "## The Understudy swap",
            "Bone Barrier is a big damage reduction lasting 20 seconds on a 30-second cooldown. Razuvious must always be hitting an Understudy that has it active.",
            "Taunt (20-second cooldown) holds him for 20 seconds. Pattern: Understudy A Barrier + Taunt -> ~18 seconds later Understudy B Barrier + Taunt -> back to A, and so on.",
            "Unbalancing Strike (every 20 seconds) hits his target extremely hard and lowers its defense - a player tank cannot take it.",
            "## Raid damage",
            "Disrupting Shout every 15 seconds: physical damage to everyone near him and mana burn.",
            "Jagged Knife every 10 seconds on a random player: damage plus a 5-second bleed.",
            "[25] If a Mind Control breaks early, re-cast it at once or have the spare Understudy ready.",
        },
        tank = {
            "[10] Controlling an Understudy is the tank job here: Bone Barrier first, then Taunt; spam Blood Strike while you hold him; call your swap 2-3 seconds before Barrier ends.",
            "[25] You hold the 2 spare Understudies away from the raid. Never tank Razuvious with your own character.",
        },
        heal = {
            "Top priority: the Understudy that currently has Razuvious. Heal it hard during the 10 seconds when Bone Barrier is on cooldown, if a swap is late.",
            "Keep the raid topped through Disrupting Shout every 15 seconds and heal Jagged Knife targets (bleed for 5 seconds).",
            "[25] Priests on Mind Control: stay within range of your Understudy and keep your own health up - Razuvious can hit you if the Understudy dies.",
        },
        dps = {
            "Attack Razuvious from behind. Stay within reason on threat - the Understudies don't generate much.",
            "Ranged: stand far enough away to limit Disrupting Shout damage on yourself.",
            "[25] Leave the spare Understudies alone.",
        },
        abilities = {
            { ids = { 55543, 29107 }, name = "Disrupting Shout", desc = "Every 15 seconds: physical damage and mana burn on everyone near Razuvious." },
            { id = 55550, name = "Jagged Knife", desc = "Every 10 seconds on a random player: damage plus a 5-second bleed." },
            { kind = "debuff", id = 26613, name = "Unbalancing Strike", desc = "Every 20 seconds on his target: a huge hit that lowers defense. Only a Bone Barrier Understudy survives it." },
            { kind = "buff", id = 29061, name = "Bone Barrier", desc = "Understudy ability: large damage reduction for 20 seconds, 30-second cooldown." },
            { id = 29060, name = "Taunt", desc = "Understudy ability: forces Razuvious to attack it for 20 seconds. 20-second cooldown." },
        },
    },
    {
        name = "Gothik the Harvester",
        npcId = 16060,
        tldr = "Survive about 4 and a half minutes of add waves, then kill Gothik. Either split the raid between the living and undead sides, or stay together on one side - after 2 minutes the gate opens if nobody is on the other side.",
        start = {
            "Two options. Split: send a balanced group to each side; the undead side needs more AoE. Stack: everyone on the living side - the gate opens at the 2-minute mark and the undead adds come over.",
            "Tanks: one per side (split) or two on the living side (stack). Have AoE and stuns ready.",
        },
        general = {
            "## Phase 1 (about 4.5 minutes of waves)",
            "Living side waves: Unrelenting Trainees (Death Plague), Deathknights (Shadow Mark) and Riders (Shadow Bolt Volley, Unholy Aura).",
            "Every living add that dies is reborn as a stronger Spectral version on the undead side: Trainees cast Arcane Explosion, Deathknights Whirlwind, Riders Drain Life/Unholy Frenzy plus a Horse that Stomps.",
            "Split strategy: the living side must not kill faster than the undead side can handle.",
            "Stack strategy: at 2 minutes the gate opens (because nobody is on the undead side) and every Spectral add attacks - AoE them at the gate.",
            "## Phase 2",
            "Gothik comes down. He Shadow Bolts his target and casts Harvest Soul on the whole raid every 15 seconds (-10% stats per stack, stacks forever) - the soft enrage.",
            "He teleports between the two sides every 20 seconds until 30%, then the gate opens and everyone kills him.",
        },
        tank = {
            "Grab each wave as it spawns and stack the adds on top of each other for AoE.",
            "Riders hit hard and their Unholy Aura damages everyone within 45 yards - get them quickly and use a cooldown.",
            "Phase 2: pick up Gothik on whichever side he appears; the other side's tank grabs him after each teleport.",
        },
        heal = {
            "Dispel Death Plague (disease) from Trainees. The undead side (Arcane Explosion, Whirlwind, Stomp) takes the most AoE damage.",
            "Phase 2: Harvest Soul keeps stacking - raid healing gets harder every 15 seconds, so DPS must be fast.",
        },
        dps = {
            "Kill Riders and Deathknights first, AoE the Trainees.",
            "Split strategy (living side): don't kill faster than the undead side can keep up.",
            "Phase 2: kill remaining adds, then go all-in on Gothik before Harvest Soul stacks get high.",
        },
        abilities = {
            { id = 28679, name = "Harvest Soul", desc = "Phase 2, every 15 seconds: hits the whole raid and lowers all stats by 10% per stack." },
            { ids = { 29317, 56405 }, name = "Shadow Bolt", desc = "Damage on Gothik's current target." },
            { kind = "debuff", id = 27825, name = "Shadow Mark", desc = "From Unrelenting Deathknights: marks a player; Riders' Shadow Bolt Volley targets marked players." },
            { kind = "debuff", ids = { 55604, 55645 }, name = "Death Plague", desc = "A disease from Trainees. Dispel it." },
        },
    },
    {
        name = "The Four Horsemen",
        aliases = { "Thane Korth'azz", "Lady Blaumeux", "Baron Rivendare", "Sir Zeliek" },
        tldr = "Four bosses in four corners, each stacking a Mark on everyone within 45 yards. Rotate tanks/groups before the Marks get high. Stack for Korth'azz's Meteor, spread for Zeliek's Holy Wrath, move out of Blaumeux's Void Zones. Berserk at 10 minutes.",
        start = {
            "Korth'azz and Rivendare (melee) are tanked by real tanks; Blaumeux and Zeliek (casters) are 'tanked' by whoever is closest - usually ranged or hybrid tanks.",
            "Common setup: 4 tanks, two at the back (Korth'azz/Rivendare) and two at the front (Blaumeux/Zeliek), with healers and DPS split.",
            "[10] Many groups use 3 groups: both melee bosses pulled together at the back, then rotate.",
            "Someone must always be within 45 yards of Blaumeux and Zeliek, or they cast an unavoidable raid-wide punishment.",
        },
        general = {
            "## The Marks",
            "First Mark 24 seconds after the pull. Korth'azz and Rivendare mark every 12 seconds; Blaumeux and Zeliek every 15 seconds.",
            "Each Mark hits everyone within 45 yards; damage per stack grows fast (stack 4+ becomes lethal). Marks last a long time, so leave a boss and let them fall off before coming back.",
            "## Rotation",
            "Tanks/groups swap bosses at about 3 stacks. Back corner: the two tanks meet in the middle and taunt each other's boss. Front corner: groups move to the other caster boss.",
            "## Boss abilities",
            "Korth'azz: Meteor on his target, split between everyone nearby - melee stay stacked on the tank.",
            "Rivendare: Unholy Shadow on his target (damage + DoT).",
            "Blaumeux: Shadow Bolt on the nearest player and Void Zones on the ground - move out.",
            "Zeliek: Holy Bolt and Holy Wrath, which chains between nearby players - stand spread.",
            "When two Horsemen are dead, the freed groups help on the others; keep rotating by Marks.",
        },
        tank = {
            "Back corner tanks: hold Korth'azz/Rivendare, call out your stacks, and swap at 3 - taunt the incoming boss from your partner in the middle.",
            "Front corner tanks: keep Blaumeux/Zeliek on you within 45 yards; move out of Void Zones (Blaumeux) and keep others spread around you (Zeliek).",
            "Use cooldowns on high-stack Marks; never let your Marks reach 5+.",
        },
        heal = {
            "Each healer is assigned to a corner and rotates with their group. Watch your own Mark stacks too.",
            "Meteor side: stacked melee take shared fire damage. Zeliek side: spread out and heal Holy Wrath jumps.",
            "Healers can be swapped out to let Marks fall off - keep healing from range when possible.",
        },
        dps = {
            "Kill order is usually Korth'azz first, then Rivendare, then the casters (or follow your raid's plan).",
            "Melee: stay stacked on the tank for Meteor. Ranged on Zeliek: stay 10+ yards apart.",
            "Move with your group on every rotation and watch your Mark count - leave if you reach 4.",
        },
        abilities = {
            { kind = "debuff", id = 28832, name = "Mark of Korth'azz", desc = "Every 12 seconds on everyone within 45 yards; stacking damage." },
            { kind = "debuff", id = 28833, name = "Mark of Blaumeux", desc = "Every 15 seconds on everyone within 45 yards; stacking damage." },
            { kind = "debuff", id = 28834, name = "Mark of Rivendare", desc = "Every 12 seconds on everyone within 45 yards; stacking damage." },
            { kind = "debuff", id = 28835, name = "Mark of Zeliek", desc = "Every 15 seconds on everyone within 45 yards; stacking damage." },
            { ids = { 28884, 57467 }, name = "Meteor", desc = "Korth'azz: heavy fire damage split between everyone near his target. Stay stacked." },
            { ids = { 28883, 57466 }, name = "Holy Wrath", desc = "Zeliek: holy damage that jumps between nearby players. Stay spread." },
            { ids = { 28863, 57463 }, name = "Void Zone", desc = "Blaumeux: shadow pool on the ground. Move out." },
            { ids = { 28882, 57369 }, name = "Unholy Shadow", desc = "Rivendare: shadow damage and a DoT on his target." },
        },
    },
    ------------------------------------------------------------------ CONSTRUCT QUARTER
    {
        name = "Patchwerk",
        npcId = 16028,
        tldr = "Pure tank-healing and DPS check. Hateful Strike hits the highest-health player among the top #{1/2} on threat in melee range besides the main tank, so #{1/2} soak tank#{/s} stand#{s/} in melee. Berserk at 6 minutes, Frenzy at 5%.",
        start = {
            "#{2/3} tanks: one main tank and #{one soak tank/two soak tanks} in melee range, second#{/ and third} on threat and with the highest health in melee.",
            "Every healer is on the tanks - there is no raid damage.",
            "Melee DPS can stand in the slime around the room to lower their health so Hateful Strike never picks them.",
        },
        general = {
            "Hateful Strike (every second) hits the player with the most health among the top #{1/2} threat targets in melee range, excluding the main tank. That's the soak tank's job.",
            "The soak tank must stay in melee range and above every melee DPS on threat (use Misdirection / Tricks of the Trade on them at the start).",
            "At 5% he Frenzies (40% faster attacks, 25% more damage). At 6 minutes he Berserks and starts Slime Bolting - a wipe.",
        },
        tank = {
            "Main tank: build threat; nothing to move.",
            "Soak tank#{/s}: stay in melee range, stay 2nd#{/ and 3rd} on threat, and keep your health pool the highest (health trinket, Last Stand / Survival Instincts / Shield Wall during big healer gaps).",
        },
        heal = {
            "Every healer on the tanks; assign healers to each soak tank - Hateful Strike hits for a lot every second.",
            "Stay out of melee range so you can't be picked.",
            "Heroism/Bloodlust and mana cooldowns when the raid calls them.",
        },
        dps = {
            "Use every cooldown and Bloodlust/Heroism - 6-minute hard enrage.",
            "Melee: keep your threat below the soak tank#{/s} and stand in the slime if your health is high.",
            "Don't pass the soak tanks on threat or you'll eat a Hateful Strike.",
        },
        abilities = {
            { ids = { 28308, 59192 }, name = "Hateful Strike", desc = "Every second: a massive hit on the highest-health player among the top #{1/2} threat in melee (not the main tank). Soak tanks take it." },
            { kind = "buff", id = 26662, name = "Berserk", desc = "At 6 minutes he becomes unbeatable - kill him before this." },
            { kind = "buff", id = 28131, name = "Frenzy", desc = "At 5% health: 40% faster attacks and 25% more damage." },
        },
    },
    {
        name = "Grobbulus",
        npcId = 15931,
        tldr = "Tank him along the outer edge, facing away, and move him a bit every Poison Cloud. Off-tank and DPS kill the Fallout Slimes. A player with Mutating Injection walks out to the edge/last cloud before it explodes.",
        start = {
            "Main tank pulls Grobbulus to the outer edge of the room and turns him away from the raid. Plan a slow clockwise walk around the edge.",
            "Off-tank stands near him ready for Fallout Slimes. Healers stand in the middle of the room.",
            "Berserk at #{12/9} minutes.",
        },
        general = {
            "Poison Cloud (every 15 seconds) is dropped under Grobbulus and stays - walk him a little way along the edge each time so clouds don't fill the room.",
            "Slime Spray (every 20 seconds) hits everyone in front of him and spawns a Fallout Slime for each player hit - only the tank should ever be in front.",
            "Mutating Injection: a 10-second debuff on a random player. When it ends (or is dispelled) it explodes for nature damage and leaves a poison cloud where you stand. Run to the edge next to the existing clouds before it ends.",
            "Injections get more frequent as his health drops.",
        },
        tank = {
            "Keep him facing away from everyone so Slime Spray only makes one Slime.",
            "Move him a few yards along the outer edge after each Poison Cloud, always in the same direction.",
            "Off-tank: pick up every Fallout Slime immediately - they damage everyone within 10 yards.",
        },
        heal = {
            "Heal through Slime Spray on the tank. Do NOT dispel Mutating Injection unless the player is already in the right spot - dispelling makes it explode where they stand.",
            "Heal the injected player after their explosion.",
        },
        dps = {
            "Kill Fallout Slimes as soon as the off-tank has them.",
            "Mutating Injection on you: walk to the edge near the last cloud, away from the raid, and wait for it to expire; then come back.",
            "Never stand in front of Grobbulus.",
        },
        abilities = {
            { ids = { 28157, 54364 }, name = "Slime Spray", desc = "Every 20 seconds: damages players in front of him and spawns a Fallout Slime per player hit." },
            { kind = "debuff", id = 28169, name = "Mutating Injection", desc = "10-second debuff; when it ends or is dispelled it explodes and leaves a poison cloud. Walk to the edge first." },
            { ids = { 28240 }, name = "Poison Cloud", desc = "Every 15 seconds: a lasting cloud under Grobbulus. Move him so they don't fill the room." },
        },
    },
    {
        name = "Gluth",
        npcId = 15932,
        tldr = "Two tanks swap for Mortal Wound, Tranquilize his Enrage every 22 seconds, kite Zombie Chow, and after each Decimate (every #{110/90} seconds) kill every Zombie before it reaches Gluth. Berserk at 6 minutes.",
        start = {
            "Two tanks on Gluth near the middle/raid side. Zombie Chow spawn from the gates at the back: #{one/two} every 10 seconds.",
            "Assign a kiting tank (Paladin/Death Knight are best) or a slow team (Frost Trap, Frost Nova, Earthbind) for the Zombies.",
            "Hunters set up a Tranquilizing Shot rotation.",
        },
        general = {
            "Mortal Wound (every 10 seconds): -10% healing taken per stack on the tank. Taunt-swap at 3-4 stacks.",
            "Enrage every 22 seconds: remove it with Tranquilizing Shot.",
            "Zombies kept away from Gluth stack Infected Wound on whoever they hit. If a Zombie reaches Gluth he eats it and heals.",
            "## Decimate (every #{110/90} seconds)",
            "Everyone and every Zombie drops to 5% health. The Zombies then walk straight to Gluth and ignore threat - stun, slow and AoE them before they get there.",
            "Healers must instantly bring the tanks back up after Decimate.",
        },
        tank = {
            "Main tanks: swap at 3-4 Mortal Wound stacks. After Decimate you're at 5% - use a cooldown (Shield Wall, Icebound Fortitude) as it lands.",
            "Zombie tank/kiter: gather Zombies with AoE threat (Consecration, Death and Decay) and keep them moving away from Gluth until Decimate.",
        },
        heal = {
            "After each Decimate, heal the Gluth tank first (he's at 5%), then the Zombie tank, then the raid.",
            "Mortal Wound reduces healing on the tanks - make sure they actually swap.",
        },
        dps = {
            "Focus Gluth until Decimate; then switch to Zombies at once (AoE, stuns, slows) - each one that reaches Gluth heals him.",
            "Hunters: Tranquilizing Shot the Enrage (every 22 seconds).",
            "Hard 6-minute enrage: save cooldowns for between Decimates.",
        },
        abilities = {
            { kind = "debuff", id = 54378, name = "Mortal Wound", desc = "Every 10 seconds on the tank: -10% healing taken per stack. Swap at 3-4 stacks." },
            { ids = { 28374, 54426 }, name = "Decimate", desc = "Every #{110/90} seconds: everyone drops to 5% health; Zombies walk to Gluth to heal him." },
            { kind = "buff", ids = { 28371, 54427 }, name = "Enrage", desc = "Every 22 seconds: faster, harder hits. Remove it with Tranquilizing Shot." },
        },
    },
    {
        name = "Thaddius",
        npcId = 15928,
        aliases = { "Feugen", "Stalagg" },
        tldr = "Phase 1: kill Feugen and Stalagg within 5 seconds of each other. Phase 2: jump to Thaddius and, after every Polarity Shift (every 30 seconds), stand with players who have the SAME charge. Berserk at 6 minutes.",
        start = {
            "Split the raid evenly between Feugen and Stalagg. Each has its own tank on its platform.",
            "Decide two sides for phase 2 (e.g. + to the left, - to the right of Thaddius) before the pull.",
        },
        general = {
            "## Phase 1: Feugen and Stalagg",
            "Every 20 seconds Magnetic Pull swaps the two tanks between platforms - each tank immediately picks up the new boss.",
            "Stalagg casts Power Surge (every 19 seconds) that makes him hit much harder; Feugen has Static Field.",
            "Don't drag either boss off its platform - the Tesla coils start shocking the raid.",
            "Bring both down evenly; when one 'dies' the other has 5 seconds to die too, or both come back at full health.",
            "## Phase 2: Thaddius",
            "After both die, everyone jumps (or walks) onto Thaddius' platform before he activates.",
            "Polarity Shift (every 30 seconds) gives everyone a + or - charge. Standing near the same charge gives a damage buff; near the opposite charge deals heavy damage to both. Move to your charge's side immediately.",
            "Chain Lightning every 15 seconds. If nobody is in melee range he casts Ball Lightning on someone.",
            "Berserk at 6 minutes.",
        },
        tank = {
            "Phase 1: hold your boss on its platform, then pick up the other boss right after each Magnetic Pull. Use a cooldown while Stalagg's Power Surge is up.",
            "Phase 2: stay in melee range so he never uses Ball Lightning, and follow the charge rule like everyone else.",
        },
        heal = {
            "Phase 1: watch your tank after each Magnetic Pull and during Power Surge.",
            "Phase 2: move to your charge side first, then heal. Chain Lightning hits up to 8 players.",
        },
        dps = {
            "Phase 1: watch both bosses' health and slow down on the one that's ahead so they die together.",
            "Phase 2: move the instant Polarity Shift is cast. Same-charge stacks give a big damage boost.",
            "Priests can Levitate and Mages Slow Fall to make the jump easier.",
        },
        abilities = {
            { kind = "debuff", id = 28089, name = "Polarity Shift", desc = "Every 30 seconds: random + or - charge on everyone. Stand with your own charge." },
            { ids = { 28167, 54531 }, name = "Chain Lightning", desc = "Every 15 seconds: lightning that jumps between players." },
            { id = 28299, name = "Ball Lightning", desc = "Used on a player when nobody is in melee range." },
            { kind = "buff", ids = { 54529, 28134 }, name = "Power Surge", desc = "Stalagg, every 19 seconds: he attacks much faster for a short time." },
            { ids = { 28135, 54528 }, name = "Static Field", desc = "Feugen: nature damage to players near him." },
            { id = 54517, name = "Magnetic Pull", desc = "Every 20 seconds: swaps the two tanks between Feugen and Stalagg." },
        },
    },
    ------------------------------------------------------------------ FROSTWYRM LAIR
    {
        name = "Sapphiron",
        npcId = 15989,
        tldr = "Ground phase: tank him sideways, decurse Life Drain, move out of Blizzard. Air phase: #{2/3} players get Icebolted into ice blocks - EVERYONE hides behind one before Frost Breath lands. Below 10% he stays on the ground. Berserk at 15 minutes.",
        start = {
            "Tank him with his back to a wall; the raid stands at his side so nobody is in front (Cleave) or behind (Tail Sweep).",
            "Frost resistance helps: Paladin Frost Resistance Aura, Shaman Frost Resistance Totem.",
            "Assign decursers for Life Drain.",
        },
        general = {
            "## Ground phase (first flight after 45 seconds)",
            "Frost Aura damages the whole raid nonstop.",
            "Life Drain (curse) on #{2/5} players - decurse quickly.",
            "Blizzard storms wander the room - move out of them.",
            "## Air phase",
            "He flies up and Icebolts #{2/3} players, freezing them into ice blocks. Stay spread so each Icebolt only hits one player.",
            "He then casts Frost Breath: everyone not hidden BEHIND an ice block (line of sight) dies. Pick your block early.",
            "After landing, the ground phase restarts. Below 10% health he stops flying.",
        },
        tank = {
            "Keep him in place with his side to the raid. Don't move him unless a Blizzard sits on you.",
            "After each landing, pick him up again right away; he lands where he took off.",
        },
        heal = {
            "Frost Aura is constant raid damage - pace your mana; it's a long fight.",
            "Decurse Life Drain and heal the cursed players.",
            "Air phase: heal the spread raid and hide behind an ice block in time for the breath.",
        },
        dps = {
            "Stand at his side - never directly in front or behind.",
            "Air phase: spread out until the Icebolts land, then go behind the nearest ice block.",
            "Decurse if you can (Mages, Druids).",
        },
        abilities = {
            { kind = "debuff", ids = { 28531, 55799 }, name = "Frost Aura", desc = "Constant frost damage to the whole raid." },
            { kind = "debuff", ids = { 28542, 55665 }, name = "Life Drain", desc = "A curse on #{2/5} players that drains health. Decurse it." },
            { kind = "debuff", id = 28522, name = "Icebolt", desc = "Air phase: freezes #{2/3} players in ice blocks. Hide behind them from Frost Breath." },
            { ids = { 28524, 29318 }, name = "Frost Breath", desc = "Air phase: lethal to everyone not hidden behind an ice block." },
            { ids = { 28547, 55699 }, spellName = "Chill", name = "Blizzard", desc = "Moving ice storms on the ground. Move out." },
            { kind = "debuff", id = 28547, name = "Chill", desc = "Blizzard's damage and slow. Avoid it." },
        },
    },
    {
        name = "Kel'Thuzad",
        npcId = 15990,
        aliases = { "Guardian of Icecrown" },
        tldr = "P1 (3:48): kill the adds while KT is untouchable. P2: spread 10 yards, interrupt Frostbolt, dodge Shadow Fissure, heal Frost Blast victims#{/, crowd-control Chained players}. P3 at 45%: tank #{2/4} Guardians of Icecrown and burn KT.",
        start = {
            "Phase 1 is add control only. Tanks pick up Unstoppable Abominations, ranged kill Soldiers of the Frozen Waste and Soul Weavers before they reach the raid.",
            "Spread the raid around the room in phase 2 positions: at least 10 yards apart.",
            "[25] Plan crowd control for Chains of Kel'Thuzad (Polymorph, Hex, Fear, Hammer of Justice).",
        },
        general = {
            "## Phase 1 (3 minutes 48 seconds)",
            "Soldiers (every ~3 seconds) explode when they reach a player. Abominations (every ~18 seconds) stack Mortal Wound on the tank. Soul Weavers (every 30 seconds) knock back and deal shadow damage.",
            "## Phase 2",
            "Frostbolt (single target, every few seconds): interrupt it - it can kill the tank.",
            "Frostbolt volley every 15-30 seconds on the whole raid.",
            "Shadow Fissure (every 25 seconds) under a player: move out immediately or it one-shots.",
            "Frost Blast (every 45 seconds) stuns a player and everyone within 10 yards and drains their health - heal them hard. #{It never targets the main tank./It can also hit the main tank.}",
            "Detonate Mana (every 30 seconds) on a mana user: they explode for shadow damage - stay spread.",
            "[25] Chains of Kel'Thuzad (every 90 seconds): Mind Controls players for 20 seconds. CC them, don't kill them.",
            "## Phase 3 (45% health)",
            "#{2/4} Guardians of Icecrown come out, about 5 seconds apart. Off-tanks pick them up. Their Blood Tap makes them grow stronger every 15 seconds - kill KT quickly.",
        },
        tank = {
            "Phase 1: tank the Abominations away from the raid; swap if Mortal Wound stacks high.",
            "Phase 2: hold KT in the middle and stay away from others (Frost Blast).",
            "Phase 3: #{one off-tank takes both Guardians/two off-tanks take two Guardians each}. Never let them reach the raid; use cooldowns as Blood Tap stacks.",
        },
        heal = {
            "Phase 2: Frost Blast victims lose a lot of health per second for 5 seconds - big, fast heals on them.",
            "Watch Frostbolt hits on the tank (when an interrupt fails) and heal the raid after each volley.",
            "Stay 10+ yards from everyone (Frost Blast, Detonate Mana).",
        },
        dps = {
            "Phase 1: ranged kill Soldiers and Weavers before they reach anyone; melee help on Abominations.",
            "Phase 2: set an interrupt rotation for Frostbolt; move out of Shadow Fissure at once; stay spread.",
            "[25] Crowd-control Chained players, never kill them.",
            "Phase 3: ignore the Guardians and burn KT.",
        },
        abilities = {
            { ids = { 28478, 55802 }, name = "Frostbolt", desc = "Big frost hit on the tank. Interrupt it." },
            { ids = { 28479, 55807 }, spellName = "Frostbolt", name = "Frostbolt Volley", desc = "Every 15-30 seconds: frost damage to the whole raid." },
            { id = 27808, name = "Frost Blast", desc = "Every 45 seconds: stuns a player and everyone within 10 yards and drains their health for 5 seconds. Stay spread." },
            { id = 27819, name = "Detonate Mana", desc = "Every 30 seconds on a mana user: they explode for shadow damage around them. Stay spread." },
            { id = 27810, name = "Shadow Fissure", desc = "Every 25 seconds under a player: one-shots anyone still in it. Move out." },
            { kind = "debuff", id = 28410, name = "Chains of Kel'Thuzad", desc = "25-man only, every 90 seconds: Mind Controls players for 20 seconds. Crowd-control them." },
        },
    },
}, "AzerothCore boss scripts (timers), Icy Veins and wowtbc.gg WotLK Classic guides (strategy)")
