-- Icecrown Citadel and The Ruby Sanctum
-- "hard" = Heroic mode. Numbers that differ by raid size use #{10-man/25-man}.
local WM = WrathMentor

WM:AddRaid("icc", "Icecrown Citadel", { "Icecrown Citadel" }, {
    {
        name = "Lord Marrowgar",
        aliases = { "Bone Spike" },
        tldr = "Side-step Coldflame (it only travels in straight lines), break impaled players out of Bone Spikes fast, tanks stack to split Bone Slice, and get out of the way during Bone Storm (every 90 seconds).",
        start = {
            "Main tank pulls him and faces him away from the raid. The off-tank stands on the main tank to split Bone Slice.",
            "The raid gathers close to the boss at the start: Coldflame begins a little away from him, so standing near him avoids the first flames. Then just watch the ground and side-step.",
            "Marrowgar has an oversized hitbox - melee can stand well within it and still be in range, which keeps them clear of most Coldflames. Keep at least 3 players (8 in 25-man) out of melee range so a Coldflame never has to pick a melee target.",
        },
        general = {
            "Bone Slice: heavy cleave on the tanks. Tanks stack together to split the damage.",
            "Coldflame: lines of cold fire that always move in a STRAIGHT LINE - simply step out of the way.",
            "Bone Spike Graveyard (every 15-20 seconds): #{1 player is/3 players are} impaled and can't act. DPS the Bone Spike immediately to free them; healers heal them up. Berserk at 10 minutes.",
            "Bone Storm (first about 45 seconds in, then every 90 seconds, lasting #{20/30} seconds): he becomes a whirlwind and moves to the players farthest away. Get out of his way. During Bone Storm he periodically stops and spawns Coldflames in a cross directly under him.",
            "On Normal mode he does NOT cast Bone Spike Graveyard while Bone Storm is active - only Heroic adds that combination, so Normal raiders only need to dodge the storm itself during that window.",
        },
        tank = {
            "Main tank and off-tank stand on top of each other in front of him to split Bone Slice (it hits the target and the nearest player); face him away from the raid.",
            "During Bone Storm he spins toward random players - drop threat worries, just stay out of his path and pick him back up when it ends.",
            "Move a few steps when Coldflame lines come toward you; they always travel straight.",
        },
        heal = {
            "Bone Spike Graveyard: impaled players take heavy damage over time - heal them until DPS break the spike.",
            "Bone Storm (#{20/30} seconds) hits anyone near him and leaves a bleed - heal the raid through it.",
            "Coldflame hits (frost) on careless players add up; Frost Resistance Aura/Totem helps.",
        },
        dps = {
            "Bone Spikes first, every time - then back to Marrowgar.",
            "Side-step Coldflame lines and stay away from his path during Bone Storm.",
            "Melee can stand deep in his large hitbox to stay safe from most Coldflames.",
        },
        abilities = {
            { ids = { 69055, 70814 }, name = "Bone Slice", desc = "A heavy cleave on the tank. Tanks stack to split it." },
            { ids = { 69146, 70823 }, name = "Coldflame", desc = "A line of cold fire that moves straight. Side-step it." },
            { kind = "debuff", ids = { 69057, 70826 }, name = "Bone Spike Graveyard", desc = "Impales a player on a spike. Kill the spike to free them." },
            { ids = { 69076, 70835 }, name = "Bone Storm", desc = "Every 90 seconds he whirls around the room for #{20/30} seconds. Stay out of his path." },
        },
        hard = {
            "Heroic: Bone Spike Graveyard continues DURING Bone Storm, so spikes and the storm must be handled at the same time.",
            "Bone Storm still comes every 90 seconds; Coldflame and spikes hit harder.",
            "Achievement challenge (WoW-Mania list): 'Boned' - defeat him without anyone staying impaled by a Bone Spike for more than 8 seconds.",
        },
    },
    {
        name = "Lady Deathwhisper",
        aliases = { "Cult Adherent", "Cult Fanatic", "Vengeful Shade" },
        tldr = "Phase 1: burn down her Mana Barrier while killing the cultist waves (interrupt Adherents, dispel Curse of Torpor, steal Fanatics' Vampiric Might). Phase 2: the shield is gone - interrupt Frostbolt, avoid Vengeful Shades, taunt-swap Touch of Insignificance.",
        start = {
            "Assign tanks to the LEFT and RIGHT sides of the room. Every minute new adds spawn: 7 in 25-man (3 on each side plus 1 from the stairs), 3 in 10-man (on one side, alternating sides each wave). Berserk at 10 minutes.",
            "[25] The LEFT side always gets 2 Fanatics and 1 Adherent; the RIGHT side always 2 Adherents and 1 Fanatic. Decide whether melee spread out or fight in one group.",
            "Save Bloodlust/Heroism for phase 1: you have to kill adds while dropping the shield.",
        },
        general = {
            "## Phase 1 (Mana Barrier up)",
            "Lady Deathwhisper is protected by a Mana Barrier: damage on her drains her mana first. When the mana is gone, phase 2 begins. Any adds still alive then must be killed in phase 2, so be careful at the transition.",
            "Adherents: interrupt Deathchill Bolt and remove Curse of Torpor. Fanatics: Necrotic Strike and Vampiric Might (Mages Spellsteal, Shamans Purge it).",
            "Adds randomly gain Shroud of the Occult, which must be broken by PHYSICAL DPS. She sometimes empowers adds: Empowered Adherents gain Deathchill Blast and can't be interrupted; Empowered Fanatics deal 100% more damage but are slowed 25% so they can be kited.",
            "Animate Dead: reanimated Fanatics take 99% less physical damage and reanimated Adherents take 99% less magic damage. Adds also use Dark Martyrdom and become reanimated after exploding.",
            "Avoid Death and Decay. Healers watch spike damage from Shadow Bolt.",
            "[25] Crowd control players targeted by Dominate Mind.",
            "## Phase 2 (shield gone)",
            "She continues Death and Decay and Dominate Mind. Interrupt Frostbolt. Healers watch the AoE from Frostbolt Volley.",
            "Move away from Vengeful Shades - they explode if they reach you.",
            "Tanks taunt off each other for Touch of Insignificance.",
        },
        tank = {
            "Add tanks: pick up each wave as it spawns (every 60 seconds#{, alternating sides/}) and pull Fanatics away from casters; Adherents can be tanked where they stand.",
            "Phase 2: two tanks on Deathwhisper. Touch of Insignificance stacks lower the tank's threat - taunt-swap at about 3 stacks.",
            "Keep adds out of Death and Decay.",
        },
        heal = {
            "Phase 1: Shadow Bolt hits random players hard; dispel Curse of Torpor from Adherents' targets.",
            "Necrotic Strike puts a heal absorb on the add tank - heal through it.",
            "Phase 2: Frostbolt Volley hits the raid; Vengeful Shades explode on whoever they touch.",
            "Dominate Mind (not in 10-man normal): a controlled player must be crowd-controlled, not killed.",
        },
        dps = {
            "Phase 1: split between the Mana Barrier and the adds; kill Adherents (interrupt Deathchill Bolt) and Fanatics before they're reanimated.",
            "Physical DPS break Shroud of the Occult. Spellsteal/Purge Vampiric Might.",
            "Phase 2: interrupt Frostbolt, move away from Vengeful Shades, then burn her.",
            "Never stand in Death and Decay.",
        },
        abilities = {
            { kind = "buff", id = 70842, name = "Mana Barrier", desc = "Her shield: damage drains her mana. When empty, phase 2 begins." },
            { ids = { 71001, 72108 }, name = "Death and Decay", desc = "A green ground area. Step out of it." },
            { kind = "debuff", id = 71289, name = "Dominate Mind", desc = "Mind Controls a player. Crowd control them." },
            { id = 70594, name = "Deathchill Bolt", desc = "An Adherent cast. Interrupt it." },
            { kind = "debuff", id = 71237, name = "Curse of Torpor", desc = "Adherents' curse that increases spell cooldowns. Remove it." },
            { kind = "debuff", id = 70659, name = "Necrotic Strike", desc = "A Fanatic strike that absorbs healing." },
            { kind = "buff", id = 70674, name = "Vampiric Might", desc = "A Fanatic buff. Spellsteal or Purge it." },
            { kind = "buff", id = 70768, name = "Shroud of the Occult", desc = "An add buff that physical DPS must break." },
            { kind = "debuff", id = 71204, name = "Touch of Insignificance", desc = "Reduces the tank's threat. Taunt-swap." },
            { id = 71420, name = "Frostbolt", desc = "Phase 2 frost bolt. Interrupt it." },
        },
        hard = {
            "Heroic: adds continue to spawn on ONE side of the room during phase 2, and Vengeful Shades do an AoE explosion instead of a single-target one.",
            "Heroic: Lady Deathwhisper becomes immune to Taunt in phase 2 - tanks must hold threat normally.",
            "Achievement challenge (WoW-Mania list): 'Full House' - defeat her with at least five different types of cultists alive.",
        },
    },
    {
        name = "Icecrown Gunship Battle",
        aliases = { "Muradin Bronzebeard", "High Overlord Saurfang" },
        tldr = "Use cannons on the enemy ship and AoE the boarders; when your cannons freeze, send a small team (melee, tank, healer) with Jetpacks to kill the enemy Mage, then fly back.",
        start = {
            "Everyone equips a Jetpack before the fight. Assign cannon crews (they use Cannon Blast and Incinerating Blast).",
            "Assign the boarding team beforehand: melee DPS, a tank and healers who will fly to the enemy ship to kill the Mage.",
        },
        general = {
            "Gunship Cannons: Cannon Blast builds Heat; Incinerating Blast spends Heat to prevent overheating.",
            "AoE the adds that spawn on your ship. Melee watch for Bladestorm from Sergeants. Adds become stronger the longer they live, so kill them fast.",
            "Ranged DPS kill the Riflemen on the enemy ship.",
            "Throughout the fight your cannons freeze and become unusable. You must kill the MAGE on the enemy ship to free them. Send the boarding group with Jetpacks, kill the Mage as quickly as possible (the enemy Commander gains a stacking damage buff that eventually becomes untankable), then Jetpack back.",
            "Avoid enemy rockets on the ground while on your ship.",
        },
        tank = {
            "One tank stays on your ship and picks up the boarding Sergeants and Marines/Reavers, facing them away (Bladestorm).",
            "One tank jetpacks over with the boarding team and holds the enemy Commander (Muradin/Saurfang) while the team kills the Mage. His damage stacks up the longer you stay - don't linger.",
        },
        heal = {
            "Ship healers: heal the cannon crews and the tank on your ship (rockets and boarders).",
            "Boarding healer: keep the boarding tank alive against the Commander - jump back with the team as soon as the Mage dies.",
        },
        dps = {
            "Cannon players: Cannon Blast to build heat, Incinerating Blast to spend it; shoot the enemy ship and boarders.",
            "Ranged on your ship: kill the Riflemen/Mortar soldiers on the enemy ship.",
            "Boarding team: when the cannons freeze, jetpack over, kill the Battle-Mage, and jetpack back. Kill boarders on your deck quickly - they get stronger the longer they live.",
        },
        abilities = {},
        hard = {
            "Heroic: enemies deal higher damage all around, so healing on the tank matters more.",
            "Slow missiles with a knockback appear; dodge them. Portal-spawned adds must be picked up by a tank.",
            "Achievement challenge (WoW-Mania list): \"I'm on a Boat\" - win the fight without any raid member visiting the enemy ship more than twice.",
        },
    },
    {
        name = "Deathbringer Saurfang",
        aliases = { "Blood Beast" },
        tldr = "Ranged spread for Blood Nova, tanks swap on Rune of Blood, kite and single-target the Blood Beasts (they have Resistant Skin), and keep the Mark of the Fallen Champion target alive.",
        start = {
            "Two tanks who will taunt off each other. Ranged spread out. Assign Blood Beast kiters/killers (Ranged DPS with single-target damage).",
            "Save Bloodlust/Heroism for a moment when the Blood Beasts are under control.",
        },
        general = {
            "He has two passive abilities, Blood Link and Blood Power. When Blood Power hits 100 he casts Mark of the Fallen Champion on a random player.",
            "Mark of the Fallen Champion: the marked player MUST be kept alive - if they die, Saurfang heals for 5% of his health on normal (20% on heroic).",
            "30 seconds in and then every 40 seconds #{2/5} Blood Beasts spawn around him. They must be kited and killed by Ranged DPS. They have Resistant Skin, so use single-target abilities. Blood Beasts can be slowed and stunned (Frost Trap, Frost Nova, Hammer of Justice).",
            "Melee: be careful with AoE like Divine Storm just before Blood Beasts spawn so you don't pull aggro.",
            "Ranged stay spread out to mitigate Blood Nova. Healers watch players with Boiling Blood. Tanks taunt off each other when afflicted by Rune of Blood.",
            "At 30% health he uses Frenzy.",
        },
        tank = {
            "Two tanks: Rune of Blood heals Saurfang and builds his Blood Power - taunt-swap on every Rune of Blood.",
            "Keep him in place; Blood Beasts should never reach the tanks or melee.",
            "Frenzy at 30%: use cooldowns.",
        },
        heal = {
            "Mark of the Fallen Champion: that player takes extra damage from every Saurfang hit - keep them alive; their death heals Saurfang.",
            "Boiling Blood (DoT on random players) and Blood Nova (hits a player and those near them) - spread healing.",
            "Blood Power grows whenever he or his Blood Beasts hit players - staying spread for Blood Nova and killing Beasts fast delays the next Mark.",
        },
        dps = {
            "Blood Beasts (#{2/5} every 40 seconds): ranged slow/stun and kill them with single-target damage before they reach anyone (they gain Blood Power for Saurfang when they hit).",
            "Melee stay on Saurfang; avoid AoE right before Beasts spawn so they don't come to you.",
            "Berserk at 8 minutes on normal (6 on heroic) - push DPS.",
        },
        abilities = {
            { kind = "buff", id = 72371, name = "Blood Power", desc = "Saurfang's growing power. At 100 he casts Mark of the Fallen Champion." },
            { kind = "debuff", id = 72410, name = "Rune of Blood", desc = "A debuff on the tank. Swap tanks." },
            { kind = "debuff", id = 72385, name = "Boiling Blood", desc = "A damage-over-time on players. Heal through it." },
            { id = 72378, name = "Blood Nova", desc = "Damage on players around a target. Stay spread." },
            { kind = "debuff", id = 72293, name = "Mark of the Fallen Champion", desc = "Marks a player; if the player dies he heals Saurfang." },
            { kind = "buff", id = 72723, name = "Resistant Skin", desc = "Blood Beasts resist AoE. Use single-target damage." },
            { kind = "buff", id = 72737, name = "Frenzy", desc = "At 30% health he attacks faster." },
        },
        hard = {
            "Heroic: Mark of the Fallen Champion heals him for 20% of his health instead of 5% - the marked player must not die at all.",
            "Heroic: Blood Beasts cast Scent of Blood shortly after spawning.",
        },
    },
    {
        name = "Festergut",
        tldr = "Stack on a Gas Spore holder to earn Inoculated stacks before Pungent Blight, then spread out. Tanks taunt at 9 stacks of Gastric Bloat. Enrage after 5 minutes.",
        start = {
            "Two tanks to swap on Gastric Bloat (at 9 stacks). Ranged spread out for Vile Gas.",
            "Healers expect steady raid damage from Gaseous Blight - it gets lower with every Inhale Blight but tank damage increases.",
        },
        general = {
            "Festergut enrages after 5 minutes.",
            "Heal raid-wide damage from Gaseous Blight. Ranged stay spread out so Vile Gas doesn't hit several players.",
            "Gastric Bloat stacks on tanks: they must Taunt off each other at 9 stacks or the boss explodes and wipes the raid.",
            "Inhale Blight: reduces the damage of Gaseous Blight (raid damage decreases, tank damage increases).",
            "Gas Spore: #{2/3} random players are infected and it detonates after 12 seconds. EVERYONE stacks on a player with Gas Spore to receive a stacking buff (Inoculated) that protects against Pungent Blight, then spreads out again.",
            "About 30 seconds after the THIRD Inhale Blight, Festergut casts Pungent Blight: it removes your buff stacks, removes Festergut's damage buff and releases Gaseous Blight back into the room.",
            "Mages (Ice Block) and Shadow Priests (Dispersion) can survive Pungent Blight and ignore stacking. Paladin tanks can remove Gastric Bloat with Divine Shield.",
        },
        tank = {
            "Two tanks: Gastric Bloat stacks on the current tank (every ~15 seconds); taunt-swap at 9 stacks or the tank explodes at 10.",
            "Stay with the raid stack for Gas Spores when you can - tanks need Inoculated stacks for Pungent Blight too.",
            "His damage on the tank goes up with each Inhale Blight.",
        },
        heal = {
            "Gaseous Blight raid damage is highest at the start and drops with each Inhale Blight (every ~34 seconds).",
            "Pungent Blight (after the third Inhale) is massive raid damage: everyone should have Inoculated stacks; save raid cooldowns for it.",
            "Vile Gas hits several ranged players and makes them vomit - heal them.",
        },
        dps = {
            "Gas Spore on #{2/3} players: everyone stacks on a spore player before it explodes to get Inoculated, then spreads again.",
            "Ranged stay spread out (8+ yards) for Vile Gas.",
            "Berserk at 5 minutes - this is a DPS race; Bloodlust early.",
        },
        abilities = {
            { kind = "debuff", ids = { 69159, 70136, 69157, 69162, 69163 }, name = "Gaseous Blight", desc = "Raid-wide damage that fades as Inhale Blight stacks." },
            { kind = "buff", id = 69165, name = "Inhale Blight", desc = "Festergut inhales the gas; three of these lead to Pungent Blight." },
            { id = 69195, name = "Pungent Blight", desc = "Lethal blast after the third Inhale unless you have Inoculated stacks." },
            { kind = "debuff", ids = { 72219, 72551 }, name = "Gastric Bloat", desc = "A stacking debuff on tanks that explodes at 10. Swap at 9." },
            { kind = "debuff", id = 69240, name = "Vile Gas", desc = "Hits several ranged players. Stay spread." },
            { kind = "debuff", id = 69279, name = "Gas Spore", desc = "Players are infected and it detonates after 12 seconds. Stack on them." },
        },
        hard = {
            "Heroic: Professor Putricide periodically throws Malleable Goo at random players from the balcony - dodge it. It can land while you are stacking for the Gas Spore explosion, so react accordingly.",
        },
    },
    {
        name = "Rotface",
        aliases = { "Little Ooze", "Big Ooze" },
        tldr = "Avoid Slime Spray. The off-tank kites the Big Ooze around the outer edge; players with Mutated Infection run into the Big Ooze's path so their Small Ooze merges into it. The Big Ooze dies after 5 merges.",
        start = {
            "Main tank on Rotface. Off-tank on the first two Small Oozes before they merge, then kites the Big Ooze around the OUTER EDGE of the room.",
            "Everyone knows the Ooze Flood covers one outer quarter of the room at a time.",
        },
        general = {
            "Avoid Slime Spray. Ooze Flood covers an outer quarter of the room at times (each quarter is covered at least once before repeating); the off-tank can run through it while kiting (Paladins can Hand of Freedom).",
            "Mutated Infection lands on random players. When it is cleansed or expires it spawns a Small Ooze.",
            "Two Small Oozes merge into a Big Ooze; a Big Ooze gets a stacking damage buff every time it merges with a Small Ooze. After 5 merges it uses Unstable Ooze Explosion and kills itself.",
            "Players with Mutated Infection must run in front of the off-tank's path so when they're cleansed the Big Ooze runs into the new Small Ooze and merges.",
            "Be careful not to merge two Small Oozes when you already have a Big Ooze alive.",
        },
        tank = {
            "Main tank: hold Rotface in the middle; Slime Spray (every 20 seconds) is a cone toward a random player - don't let it hit the raid.",
            "Ooze tank: pick up the Little Oozes from infected players and walk the merged Big Ooze slowly around the outer edge, always the same direction.",
            "When a Big Ooze reaches 5 merges it explodes (Unstable Ooze Explosion) - move away from where it's about to burst.",
        },
        heal = {
            "Mutated Infection on random players (faster as the fight goes on): it deals damage and reduces healing taken; when it's dispelled or expires it drops a Little Ooze.",
            "Only dispel Mutated Infection when the player is standing near the ooze tank's path.",
            "Sticky Ooze puddles slow and damage - heal and call out those standing in them.",
        },
        dps = {
            "Move out of Slime Spray (the cone in front of Rotface's target).",
            "Infected? Run to the ooze tank's path so your Little Ooze merges into the Big Ooze.",
            "Never AoE the Big Ooze, and stay away from it and its explosion.",
        },
        abilities = {
            { id = 69508, name = "Slime Spray", desc = "A frontal spray on Rotface's target. Avoid the cone." },
            { kind = "debuff", id = 69674, name = "Mutated Infection", desc = "A disease on random players; spawns a Small Ooze when it ends or is cleansed." },
            { id = 69839, name = "Unstable Ooze Explosion", desc = "A Big Ooze explodes after 5 merges." },
            { kind = "debuff", id = 72272, name = "Vile Gas", desc = "Heroic: Putricide casts this on ranged players." },
        },
        hard = {
            "Heroic: Professor Putricide periodically casts Vile Gas at random ranged players from the balcony, so stay spread out just like on Festergut.",
        },
    },
    {
        name = "Professor Putricide",
        aliases = { "Volatile Ooze", "Gas Cloud", "Mutated Abomination" },
        tldr = "P1: an off-tank drives the Mutated Abomination and slows the Volatile Ooze / Gas Cloud that hunt one player. Stack on the Volatile Ooze target, kite the Gas Cloud and kill both. P2: 80% - Choking Gas Bomb and Malleable Goo. P3: 35% - Mutated Plague, three tanks.",
        start = {
            "The off-tank clicks the table to gain control of the Mutated Abomination (Eat Ooze on Mutated Slime; Regurgitated Ooze slows adds).",
            "Putricide alternates a Volatile Ooze (from the Green Tank) and a Gas Cloud (from the Orange Tank). The Volatile Ooze comes FIRST, so start with Putricide tanked near the ORANGE tank.",
        },
        general = {
            "## Phase 1",
            "Volatile Ooze casts Volatile Ooze Adhesive on a random player when it spawns, rooting them. The raid stacks on that player so the explosion is split, and kills the Ooze.",
            "After killing the Ooze, the whole raid moves toward the Green Tank because a Gas Cloud spawns from the Orange Tank shortly.",
            "The Gas Cloud puts Gaseous Bloat on a random player, starting at 10 stacks and losing 1 every 2 seconds. If the Cloud reaches you it does more damage the more stacks you have: kill it before that.",
            "The Mutated Abomination driver uses Regurgitated Ooze to slow the Ooze/Cloud.",
            "## Phase 2 (80% health)",
            "Same as phase 1, plus Choking Gas Bomb (move away before it explodes) and Malleable Goo (ranged dodge it).",
            "## Phase 3 (35% health)",
            "Adds stop spawning but Choking Gas Bomb and Malleable Goo continue; kill remaining adds. The Mutated Abomination despawns and the off-tank helps tank Putricide because of Mutated Plague. Mutated Slime now fills the room.",
            "THREE tanks are recommended: Mutated Plague stacks add raid-wide damage, so taunt off each other every stack.",
        },
        tank = {
            "Main tank: hold Putricide between the two tanks of ooze. In phase 3 three tanks taunt-swap on every Mutated Plague stack.",
            "Abomination driver (off-tank): eat Mutated Slime puddles to build energy, Regurgitated Ooze to slow the Volatile Ooze/Gas Cloud, Mutated Slash/Mutated Transformation as needed.",
        },
        heal = {
            "Volatile Ooze Adhesive target is rooted; the Ooze explodes on them and everyone near - stack on them so the damage is shared.",
            "Gaseous Bloat target runs from the Gas Cloud; the longer it chases, the less damage - heal them.",
            "Phase 3: Mutated Plague adds raid damage per stack - tanks must swap. Heroic: pass Unbound Plague.",
        },
        dps = {
            "Volatile Ooze: everyone stacks on the target to split the explosion, then kill the Ooze.",
            "Gas Cloud: the Gaseous Bloat target kites it, everyone else kills it.",
            "Phase 2+: move away from Choking Gas Bombs and dodge Malleable Goo.",
            "Berserk at 10 minutes.",
        },
        abilities = {
            { id = 72527, name = "Eat Ooze", desc = "Mutated Abomination ability that consumes Mutated Slime on the ground." },
            { ids = { 70539, 72457, 72875, 72876 }, name = "Regurgitated Ooze", desc = "Slows the Ooze or Cloud." },
            { kind = "debuff", id = 70447, name = "Volatile Ooze Adhesive", desc = "The Ooze sticks to a player and explodes when it reaches them." },
            { kind = "debuff", id = 70672, name = "Gaseous Bloat", desc = "Marks a player for the Gas Cloud; damage scales with stacks." },
            { id = 71255, name = "Choking Gas Bomb", desc = "Bombs on the ground that explode. Move away." },
            { id = 72295, name = "Malleable Goo", desc = "Goo thrown at players. Ranged dodge it." },
            { kind = "debuff", id = 72451, name = "Mutated Plague", desc = "A stacking tank debuff with raid damage in phase 3." },
            { kind = "debuff", id = 70911, name = "Unbound Plague", desc = "Heroic: a passing plague on a random player." },
        },
        hard = {
            "Heroic, all phases: Professor Putricide casts Unbound Plague on a random player. After taking a few ticks, pass it to another player who doesn't have the Plague Sickness debuff.",
            "Heroic, phase 2 and 3: half the raid gets Ooze Variable and the other half gets Gas Variable, and a Volatile Ooze AND a Gas Cloud spawn. The Mutated Abomination can only slow one add, so kite effectively and DPS whichever add your debuff allows you to.",
        },
    },
    {
        name = "Blood Prince Council",
        aliases = { "Prince Valanar", "Prince Keleseth", "Prince Taldaram" },
        tldr = "Only ONE prince can be damaged at a time (Invocation of Blood switches about every 46 seconds). Valanar: spread, kill Kinetic Bombs. Taldaram: run away from Ball of Flames, raid runs with it. Keleseth's tank hits Dark Nucleus to gain Shadow Resonance.",
        start = {
            "Valanar always has Invocation of Blood at the start of the fight. Three tanks: one per prince (Keleseth's tank may be a ranged tank such as a Warlock).",
            "Ranged are assigned to shoot Valanar's Kinetic Bombs before they hit the ground.",
        },
        general = {
            "Invocation of Blood makes only one prince damageable and gives him an EMPOWERED version of one of his spells. It switches about every 46 seconds.",
            "## Prince Valanar",
            "Stay spread for Shock Vortex. For Empowered Shock Vortex, melee run out and spread when the cast starts. Assign Ranged DPS to shoot Kinetic Bombs so they don't hit the ground.",
            "## Prince Taldaram",
            "Stay spread for Glittering Sparks. If you are targeted by Ball of Flames (or Empowered Ball of Flames), RUN AWAY from it. While that player runs, the rest of the raid runs WITH the Ball of Flames to drain its power before it reaches its target.",
            "## Prince Keleseth",
            "Casts Shadow Lance and summons Dark Nucleus. His tank (may be ranged) damages the Dark Nucleus to gain Shadow Resonance; aim for at least 3 stacks to survive Empowered Shadow Lance. Ranged DPS collect and move Dark Nucleus orbs away from the boss.",
        },
        tank = {
            "One tank per prince. Valanar's and Taldaram's tanks keep them apart; Keleseth can be tanked by a ranged tank (Warlock) because he casts Shadow Lance.",
            "Keleseth's tank: pick up Dark Nucleus orbs (they give Shadow Resonance, reducing shadow damage).",
            "When Invocation of Blood moves (every ~46 seconds), the raid swaps target - tanks hold steady.",
        },
        heal = {
            "Empowered Shock Vortex (Valanar) hits the whole raid - be ready when Valanar is the active prince.",
            "Empowered Flame Ball (Taldaram) chases its target - heal the target and the raid hit by its explosion.",
            "Shadow Lance on Keleseth's tank (much bigger when empowered).",
        },
        dps = {
            "Only the prince with Invocation of Blood takes real damage - switch to him each time.",
            "Ranged: shoot Kinetic Bombs before they hit the ground.",
            "Spread for Shock Vortex; run away if a Ball of Flames targets you.",
            "Berserk at 10 minutes.",
        },
        abilities = {
            { kind = "buff", ids = { 70952, 70981, 70982 }, name = "Invocation of Blood", desc = "Makes one prince damageable and empowers one of his spells. Switches about every 46 seconds." },
            { id = 72037, name = "Shock Vortex", desc = "Valanar's vortex. Stay spread." },
            { id = 72053, name = "Kinetic Bomb", desc = "Floating bombs that explode if they hit the ground. Ranged shoot them." },
            { id = 71807, name = "Glittering Sparks", desc = "Taldaram's cone of fire damage. Stay spread." },
            { id = 71405, name = "Shadow Lance", desc = "Keleseth's damage spell on the tank." },
            { kind = "buff", id = 71943, name = "Shadow Resonance", desc = "Reduces shadow damage taken when the tank hits Dark Nucleus." },
            { kind = "debuff", id = 72999, name = "Shadow Prison", desc = "Heroic: moving while it is on you hurts. Limit movement." },
        },
        hard = {
            "Heroic: Shadow Prison - limit movement as much as possible.",
            "WoW-Mania excerpt: Keleseth's Shadow Lance hits random targets and Taldaram's empowered Flame Spheres need extra care; use Bloodlust/Heroism on the pull or after the air phase.",
        },
    },
    {
        name = "Blood-Queen Lana'thel",
        tldr = "Two tanks for Blood Mirror. Ranged stay in a semi-circle with an opening in the middle; Pact of the Darkfallen linked players run to the center. Everybody bites: a Vampiric Bite chain spreads Essence of the Blood Queen. Enrage at 5:30.",
        start = {
            "Two tanks (Blood Mirror). Ranged spread in a semi-circle but leave an opening in the CENTER of the room for the Pact of the Darkfallen link.",
            "Priests use Fear Ward and Shamans use Tremor Totem to handle Incite Terror.",
        },
        general = {
            "Healers watch Delirious Slash on the tank. Shroud of Sorrow deals raid-wide damage all fight.",
            "Twilight Bloodbolt: stay spread. Pact of the Darkfallen: linked players run to the center of the room to remove the debuff.",
            "Swarming Shadows: if targeted, run away - it follows you until the debuff expires.",
            "Every 2 minutes she flies into the air, casts Incite Terror and Bloodbolt Whirl on the whole raid. Spread out as soon as the fear ends.",
            "## Vampiric Bite",
            "15 seconds after the start she bites the highest-threat player besides the tank: they gain Essence of the Blood Queen for 60 seconds. After 60 seconds your action bar changes and you must use Vampiric Bite on another player (within 10 seconds) or you'll be Mind Controlled.",
            "Every 60 seconds afterwards, everyone with Essence must bite a player who hasn't been bitten. She has a 5:30 enrage: if everyone bites quickly, you'll have about 16 DPS with Essence around 4:30 - the best time for Bloodlust.",
        },
        tank = {
            "Two tanks stand together: Blood Mirror links the off-tank to the main tank so damage taken by one is copied to the other.",
            "Delirious Slash puts a bleed on a tank - use cooldowns on big hits.",
            "Keep her in the center so Pact of the Darkfallen pairs have room to meet.",
        },
        heal = {
            "Shroud of Sorrow damages the raid nonstop (heroic: more per bitten player).",
            "Blood Mirror: heal BOTH tanks; the off-tank takes the main tank's damage too.",
            "Air phase (about every 2 minutes): Bloodbolt Whirl hits everyone after the fear - spread out and AoE heal.",
        },
        dps = {
            "When you get Frenzied Bloodthirst, bite a non-bitten player within a few seconds (your raid's bite list) or you get Mind Controlled.",
            "Pact of the Darkfallen: linked players run to each other in the middle.",
            "Swarming Shadows on you: run to the edge leaving the trail away from the raid.",
            "Berserk at 5:30 - Bloodlust when most players are bitten.",
        },
        abilities = {
            { kind = "debuff", id = 70821, name = "Blood Mirror", desc = "Links the two tanks' damage and healing." },
            { id = 71623, name = "Delirious Slash", desc = "A heavy tank strike." },
            { kind = "debuff", id = 70986, name = "Shroud of Sorrow", desc = "Raid-wide damage the entire fight." },
            { id = 71446, name = "Twilight Bloodbolt", desc = "Bolts on players. Stay spread." },
            { kind = "debuff", id = 71340, name = "Pact of the Darkfallen", desc = "Links players; run to the center to break it." },
            { kind = "debuff", id = 71264, name = "Swarming Shadows", desc = "A shadow that follows a player. Run away." },
            { id = 71727, name = "Vampiric Bite", desc = "Bite the player to pass on Essence of the Blood Queen." },
            { kind = "buff", id = 70867, name = "Essence of the Blood Queen", desc = "A buff after a bite; you must bite within 60 seconds." },
            { kind = "debuff", id = 73070, name = "Incite Terror", desc = "Fears the raid during her air phase." },
            { id = 71772, name = "Bloodbolt Whirl", desc = "Bolts on the raid in the air phase." },
        },
        hard = {
            "Heroic: Shroud of Sorrow damage increases with each player who has the Essence of the Blood Queen buff.",
        },
    },
    {
        name = "Valithria Dreamwalker",
        aliases = { "Gluttonous Abomination", "Blistering Zombie", "Blazing Skeleton", "Risen Archmage", "Suppresser" },
        tldr = "A HEALING fight: assigned healers heal Valithria to 100%, other healers heal the raid. Assigned healers enter Nightmare Portals for Emerald Vigor. Everyone else kills adds on the left and right sides.",
        start = {
            "Assign healers to Valithria and healers to the raid. Split the raid into two groups for the left and right sides of the room.",
            "Tanks pick up Abominations; a Ranged DPS kites the Zombies.",
        },
        general = {
            "Valithria must be healed to 100% health to end the encounter. AoE the Archmages who surround her.",
            "About every 45 seconds Dream Portals spawn (Nightmare Portals on heroic) and become usable a few seconds later. Healers assigned to Valithria enter the portals and touch orbs to gain Emerald Vigor. Keep your stacks up all fight.",
            "Kill Blazing Skeletons as fast as possible (Lay Waste). Suppressers channel Suppression on Valithria - kill them.",
            "Risen Archmages cast Column of Frost, Frostbolt Volley and Mana Void: interrupt Frostbolt Volley.",
            "Zombies (Corrosion and Acid Burst) are kited by a Ranged DPS (Frost Trap, Frost Nova). Abominations are tanked; they cast Gut Spray (a cleansable disease) and spawn Rot Worms when they die.",
        },
        tank = {
            "Pick up Gluttonous Abominations and Blazing Skeletons away from Valithria and the raid; face Abominations away (Gut Spray).",
            "Abominations leave Rot Worms when they die - pick those up too.",
            "Suppressers drain Valithria's healing - make sure they get killed.",
        },
        heal = {
            "Valithria healers: heal her to 100%. Enter the Nightmare Portals (every ~45 seconds) and collect the orbs for Emerald Vigor (more healing done).",
            "Raid healers: Archmages' Frostbolt Volley, Column of Frost and Mana Void, Skeletons' Lay Waste, Blistering Zombies' Acid Burst.",
            "Cleanse Gut Spray (disease) and Corrosion stacks.",
        },
        dps = {
            "Kill order: Blazing Skeletons and Suppressers > Risen Archmages (interrupt Frostbolt Volley) > Abominations > Zombies (kite them; they explode on death).",
            "Stay out of Column of Frost and Mana Void.",
            "You can't damage Valithria - your job is keeping her safe.",
        },
        abilities = {
            { kind = "buff", id = 70873, name = "Emerald Vigor", desc = "A healing buff gained by touching the dream portal orbs. Healers need stacks." },
            { id = 70702, name = "Column of Frost", desc = "Frost pillar from Risen Archmages." },
            { id = 70759, name = "Frostbolt Volley", desc = "An Archmage cast. Interrupt it." },
            { id = 71179, name = "Mana Void", desc = "Drains mana around the Archmage." },
            { id = 69325, name = "Lay Waste", desc = "Blazing Skeletons' burst. Kill them fast." },
            { id = 70588, name = "Suppression", desc = "Suppressers channel this on Valithria. Kill them." },
            { kind = "debuff", id = 70751, name = "Corrosion", desc = "The Zombies' poison." },
            { id = 70744, name = "Acid Burst", desc = "Zombie attack." },
            { kind = "debuff", id = 70633, name = "Gut Spray", desc = "Abomination's cleansable disease." },
        },
        hard = {
            "Heroic: Valithria's health decays over time, so healing must start fast.",
            "The orbs apply a damage-over-time on heroic and DO NOT respawn: leave orbs up for future Nightmare Portals so assigned healers keep their Emerald Vigor stacks.",
            "Heroic: Frostbolt Volley drains 2,000 mana.",
        },
    },
    {
        name = "Sindragosa",
        aliases = { "Rimefang", "Spinestalker", "Ice Tomb" },
        tldr = "Ground phase: face her away, sides only, run from Blistering Cold after Icy Grip. Air phase (about every 110 seconds): break Ice Tombs and hide behind one from Frost Bombs. Phase 3 at 35%: Mystic Buffet - stand behind Ice Tombs to keep stacks low.",
        start = {
            "Tank Sindragosa facing away from the raid. The raid stands on her SIDES (Tail Smash behind, Frost Breath in front).",
            "Frost resistance (Paladin Frost Resistance Aura / Shaman Frost Resistance Totem) helps. Casters understand Unchained Magic and Instability.",
        },
        general = {
            "## Ground phase",
            "Face her away because of Frost Breath. Stand on the sides to avoid Tail Smash. Heal raid-wide damage from Frost Aura.",
            "Tanks and physical DPS watch their Permeating Chill stacks. Casters deal with the Unchained Magic debuff, which puts stacks of Instability on you when you cast.",
            "Icy Grip pulls everyone to her, and then she casts Blistering Cold: RUN AWAY from her to avoid it.",
            "## Air phase (50 seconds in, then about every 110 seconds)",
            "She marks #{2/5} players (#{2/6} on heroic) with Frost Beacon. Those players must not be near anyone when they become an Ice Tomb.",
            "She casts Frost Bomb 4 times at random locations that must be avoided by standing BEHIND an Ice Tomb.",
            "The raid damages each Ice Tomb so they break quickly after the 4th Frost Bomb - players inside start to suffer Asphyxiation.",
            "## Phase 3 (35% health)",
            "She uses all ground abilities but no longer flies, stops Frost Bomb, but keeps Frost Beacon and Ice Tomb. Standing behind an Ice Tomb is needed to limit stacks of her new ability Mystic Buffet.",
        },
        tank = {
            "Main tank: face her away from the raid; Frost Breath and Cleave in front, Tail Smash behind.",
            "Permeating Chill stacks on melee/tanks - an off-tank takes over when stacks get high.",
            "Icy Grip pulls you in too: run out of Blistering Cold with everyone (she's rooted while casting).",
        },
        heal = {
            "Frost Aura damages everyone all fight; Instability explosions on casters who cast too much.",
            "Air phase (first 50 seconds in, then about every 110 seconds): Frost Beacon on #{2/5} players (#{2/6} on heroic) - they become Ice Tombs; heal them inside if needed.",
            "Phase 3 (35%): Mystic Buffet stacks make everyone take more magic damage - hide behind tombs to reset.",
        },
        dps = {
            "Stand at her sides. Casters stop casting before Unchained Magic Instability gets too high (let stacks fall off).",
            "After Icy Grip, run 25+ yards away before Blistering Cold.",
            "Air phase: Frost Beacon targets spread out; everyone hides behind an Ice Tomb from Frost Bombs; break tombs after the last bomb.",
            "Berserk at 10 minutes.",
        },
        abilities = {
            { id = 69649, name = "Frost Breath", desc = "Frontal frost breath. Face her away from the raid." },
            { id = 71077, name = "Tail Smash", desc = "Damage behind her. Stay on her sides." },
            { kind = "debuff", id = 70084, name = "Frost Aura", desc = "Raid-wide frost damage." },
            { kind = "debuff", id = 70107, name = "Permeating Chill", desc = "A stacking debuff on tanks and physical DPS." },
            { kind = "debuff", id = 69762, name = "Unchained Magic", desc = "A debuff on casters that stacks Instability when they cast." },
            { kind = "debuff", id = 69766, name = "Instability", desc = "Stacking damage on casters with Unchained Magic." },
            { id = 70117, name = "Icy Grip", desc = "Pulls everyone to her before Blistering Cold." },
            { id = 70123, name = "Blistering Cold", desc = "Massive damage if you are near her. Run away after Icy Grip." },
            { kind = "debuff", id = 70126, name = "Frost Beacon", desc = "Marks a player to be encased in an Ice Tomb." },
            { kind = "debuff", id = 70157, name = "Ice Tomb", desc = "Encases a player in ice. Use tombs as cover; break them afterwards." },
            { id = 69846, name = "Frost Bomb", desc = "Air-phase bombs at random spots. Hide behind a tomb." },
            { kind = "debuff", id = 71665, name = "Asphyxiation", desc = "Players in a tomb take damage after the last Frost Bomb." },
            { kind = "debuff", id = 70128, name = "Mystic Buffet", desc = "A stacking debuff in phase 3. Use tombs for cover." },
        },
        hard = {
            "Heroic: Instability damage is now AoE instead of single-target, so casters spread out even more.",
        },
    },
    {
        name = "The Lich King",
        aliases = { "Raging Spirit", "Ice Sphere", "Val'kyr Shadowguard", "Shambling Horror", "Vile Spirit" },
        tldr = "P1: Necrotic Plague bounces to Shambling Horrors, tank at the platform edge. P1.5/P2.5: Remorseless Winter, Raging Spirits and Ice Spheres. P2: Val'kyr grab players (kill them) and Defile grows. P3: Harvest Souls - fight inside Frostmourne. He dies at 10%.",
        start = {
            "Tank the Lich King near the EDGE of the platform (or make sure he is there before the transition). Off-tank handles Shambling Horrors.",
            "Priest/Paladin dispels ready for Necrotic Plague. Hunters ready to Tranquilizing Shot enrages.",
        },
        general = {
            "## Phase 1",
            "Healers top off targets with Infest. Drudge Ghouls die to passive cleave. Shambling Horrors are tanked away and faced away (Shockwave) - they can be stunned. They Enrage (Tranquilizing Shot) and Frenzy at 20%.",
            "All DPS focus the Lich King; the Shambling Horrors die to Necrotic Plague.",
            "Every 30 seconds Necrotic Plague hits a random player, who runs to a Shambling Horror and gets Cleansed so the debuff jumps onto it. Every bounce gives the Lich King a stacking Plague Siphon.",
            "## Phase 1.5 (70% health)",
            "The player with Necrotic Plague at the transition moves away from the raid and gets Cleansed. He runs to the center and casts Remorseless Winter: go to the EDGE of the platform to avoid it. Spread for Pain and Suffering.",
            "Ranged kill Ice Spheres before they reach the raid (Ice Burst). Tanks pick up Raging Spirits (summoned every 20 seconds) and face them away (Soul Shriek). After the third one, he casts Quake: the raid moves away from the platform edge.",
            "## Phase 2",
            "Infest continues. Run to the center and kill any remaining Raging Spirits. Every 45 seconds #{one Val'kyr picks/three Val'kyr pick} up a random player and try to drop them off the edge: kill them on normal (on heroic, getting them below 50% makes them drop the player).",
            "Defile: stay spread to keep it from growing; try to drop it outside the inner circle. Stack in the center before a Val'kyr, spread before Defile. Rotate raid cooldowns on the tank for Soul Reaper.",
            "## Phase 2.5 (40% health)",
            "Same as phase 1.5 but Raging Spirits spawn every 15 seconds. Lasts 1 minute.",
            "## Phase 3",
            "Continue Defile and Soul Reaper. Kill remaining Raging Spirits. Every 30 seconds Vile Spirits spawn: AoE them or let an off-tank soak them (they explode on contact).",
            "Harvest Soul: on normal he teleports ONE person into Frostmourne. Ranged DPS kill Wicked Spirits in the air and everyone dodges the bombs they drop. If anyone dies inside he gains Harvested Soul. You return after 40 seconds - spread out immediately because Defile is cast when you return.",
            "He enrages after 15 minutes. The fight ends when he reaches 10% health.",
        },
        tank = {
            "Phase 1: main tank holds the Lich King near the platform edge (for the transition); off-tank takes Shambling Horrors (face away for Shockwave; they Enrage - Tranquilizing Shot).",
            "Transitions: tanks pick up Raging Spirits (every 20 seconds, 15 seconds in the second transition) and face them away (Soul Shriek).",
            "Phase 2/3: Soul Reaper (every ~30 seconds) is a huge hit plus a haste buff for him - taunt-swap after every Soul Reaper.",
        },
        heal = {
            "Infest hits everyone and keeps ticking until you're above 90% health - heal everyone above 90% fast.",
            "Necrotic Plague (every 30 seconds): heal the target until it's dispelled near a Shambling Horror.",
            "Phase 2: Val'kyr carry players to the edge; Defile hits everyone standing in it (it grows when it hits people).",
            "Phase 3: Harvest Soul (every 75 seconds) takes a player into Frostmourne - the raid must keep healing outside.",
        },
        dps = {
            "Phase 1: Lich King first; Shambling Horrors die to Necrotic Plague bounces.",
            "Transitions: ranged kill Ice Spheres before they reach the raid; everyone stays away from the middle (Remorseless Winter).",
            "Phase 2: #{1 Val'kyr/3 Val'kyr} every 45 seconds grab#{s/} players - kill them (heroic: drop them below 50%) before they reach the edge. Move out of Defile at once.",
            "Phase 3: AoE Vile Spirits (every 30 seconds) or let them hit a tank; Lich King until he reaches 10%.",
        },
        abilities = {
            { kind = "debuff", id = 70541, name = "Infest", desc = "Damage on everyone below 90% health. Heal up." },
            { kind = "debuff", id = 70337, name = "Necrotic Plague", desc = "A plague on a random player, bounces when cleansed. Run to a Shambling Horror." },
            { kind = "buff", id = 74074, name = "Plague Siphon", desc = "The Lich King gains a stack every time Necrotic Plague bounces." },
            { id = 72149, name = "Shockwave", desc = "Shambling Horrors' frontal shockwave. Face them away." },
            { id = 68981, name = "Remorseless Winter", desc = "Transition phase: go to the edge of the platform." },
            { id = 72133, name = "Pain and Suffering", desc = "Spread damage in the transition phases." },
            { id = 69242, name = "Soul Shriek", desc = "A Raging Spirit's scream. Tanks face them away." },
            { id = 72262, name = "Quake", desc = "The platform shatters. Move away from the edge." },
            { id = 72762, name = "Defile", desc = "A growing pool of death. Spread to control it and run out." },
            { id = 69409, name = "Soul Reaper", desc = "A heavy tank hit. Use cooldowns." },
            { id = 73488, name = "Life Siphon", desc = "Heroic: Val'kyr drain in the air. Tanks taunt them." },
            { id = 68980, name = "Harvest Soul", desc = "Takes a player into Frostmourne." },
            { kind = "buff", ids = { 72679, 74318 }, name = "Harvested Soul", desc = "A stacking buff he gains if someone dies in Frostmourne." },
        },
        hard = {
            "Heroic: Shadow Trap in phase 1 - stay spread out and move away when targeted.",
            "Heroic phase 2: Val'kyr cast Life Siphon while carrying a player - tanks must Taunt them.",
            "Heroic phase 3: at the start of the phase, and about every 1:45 afterwards, he casts Harvest Souls and teleports the ENTIRE raid to Frostmourne (instead of just one person on normal). Everyone stays alive for 40 seconds; each death makes him stronger.",
            "Fight inside Frostmourne: Ranged DPS kill the Wicked Spirits in the air, and everyone dodges the bombs they drop.",
        },
    },
}, "AzerothCore boss scripts (timers, counts), Icy Veins and wowtbc.gg guides")

WM:AddRaid("rs", "The Ruby Sanctum", { "The Ruby Sanctum" }, {
    {
        name = "Saviana Ragefire",
        tldr = "Only the tank stands in front. Remove her Enrage with Tranquilizing Shot / Anesthetic Poison. When she flies up, everyone spreads at once - Flame Beacon players run out and avoid cleaving others.",
        start = {
            "Tank her facing away from the raid; everyone else stands at her sides (Flame Breath). A Hunter (Tranq Shot) or Rogue (Anesthetic Poison) is ready for the Enrage.",
        },
        general = {
            "Flame Breath: massive damage in a frontal cone - only the tank is ever in front.",
            "Enrage: if left on, her attack speed goes up 150% and a Fire Nova erupts from her every 2 seconds. Remove with Tranquilizing Shot or Anesthetic Poison.",
            "Air phase (every 50 seconds): she marks #{3/6} players with Flame Beacon and after a brief delay deals massive damage to them and anyone around them. Everyone spreads as soon as she takes flight; marked players avoid cleaving nearby allies and use movement abilities (Disengage, Nitro Boosts).",
        },
        tank = {
            "Face her away from the raid; Flame Breath only hits you.",
            "She Enrages often (every 15-20 seconds) - make sure a Hunter/Rogue removes it, or use cooldowns while it's up.",
            "When she lands after the air phase, pick her up quickly.",
        },
        heal = {
            "Air phase (every 50 seconds): Conflagration / Flame Beacon on #{3/6} players - they take heavy fire damage; spread so it doesn't hit others.",
            "Fire Nova from Enrage hits the whole raid if it isn't removed.",
        },
        dps = {
            "Hunters: Tranquilizing Shot every Enrage. Rogues: Anesthetic Poison helps.",
            "Stay at her sides; spread out the moment she flies.",
            "Marked in the air phase? Move away from everyone.",
        },
        abilities = {
            { id = 8873, name = "Flame Breath", desc = "Frontal fire cone. Only the tank is in front." },
            { kind = "buff", id = 78722, name = "Enrage", desc = "Dramatically increases attack speed and spawns Fire Novas. Tranq Shot or Anesthetic Poison removes it." },
            { kind = "debuff", id = 74453, name = "Flame Beacon", desc = "Marks players in the air phase; they and those nearby take massive damage." },
            { id = 61657, name = "Fire Nova", desc = "Erupts from her while Enraged." },
        },
        hard = {
            "Heroic: her abilities hit harder and the air phase is more demanding - be pre-spread and use movement abilities for Flame Beacon targets.",
        },
    },
    {
        name = "Baltharus the Warborn",
        aliases = { "Baltharus Clone" },
        tldr = "Only the tank stands in front for Blade Tempest. He clones himself at 50% health in 10-man (66% and 33% in 25-man) with a knockback stun each time - kill the ORIGINAL Baltharus and tank the clone. Spread when you have Enervating Brand.",
        start = {
            "Bring at least two tanks. Tank him facing away from the raid; everyone else stands at his sides.",
        },
        general = {
            "Blade Tempest: he twirls his weapons in front of him for massive damage - only the tank stands in front.",
            "Summon Clone: at 50% health in 10-man, or at 66% and 33% in 25-man, Baltharus summons a clone of himself. The clone should be picked up by the off-tank; the raid keeps attacking the ORIGINAL Baltharus.",
            "Repelling Wave: while summoning the clone he knocks every player back with fire damage and a 3-second stun. It is unavoidable - just prepare for the downtime.",
            "Enervating Brand: targets a random player, siphoning damage from them and nearby allies. It reduces their damage by 2% and increases Baltharus' damage: marked players spread away from allies.",
        },
        tank = {
            "Main tank holds the real Baltharus facing away (Blade Tempest, Cleave).",
            "Off-tank picks up each clone (at 50% in 10-man, 66% and 33% in 25-man) and holds it away from the raid.",
            "Repelling Wave knocks everyone back and stuns them for 3 seconds when a clone appears - pick up again right after.",
        },
        heal = {
            "Enervating Brand (#{2/4} players): drains damage from people around them to buff Baltharus - branded players spread.",
            "Heal after each Repelling Wave knockback.",
            "Two bosses hitting tanks after the clone spawns - more tank healing.",
        },
        dps = {
            "Kill the clone(s) or the boss per your raid's plan - the clone has the remaining share of health; both must die.",
            "Branded players move away from everyone.",
            "Never stand in front (Blade Tempest).",
        },
        abilities = {
            { id = 75125, name = "Blade Tempest", desc = "A frontal whirl of blades. Only the tank is in front." },
            { id = 74511, name = "Summon Clone", desc = "Baltharus summons a clone. Ignore/tank it and kill the original." },
            { id = 74509, name = "Repelling Wave", desc = "Knocks everyone back and stuns them for 3 seconds." },
            { kind = "debuff", id = 74502, name = "Enervating Brand", desc = "A brand that drains damage from you and nearby allies and boosts Baltharus. Spread out." },
        },
        hard = {
            "Heroic: the clones and Enervating Brand are more dangerous - keep clone handling clean and spread quickly for the Brand.",
        },
    },
    {
        name = "General Zarithrian",
        aliases = { "Onyx Flamecaller" },
        tldr = "Tank-swap before Cleave Armor stacks kill the tank. Onyx Flamecallers enter from both sides in waves: tanks pick them up and everyone interrupts Lava Gout. Intimidating Roar is a 4-second FEAR - Tremor Totem/Fear Ward stop it.",
        start = {
            "Saviana AND Baltharus must both be dead before you can engage Zarithrian.",
            "Assign tanks for the Flamecaller waves on the left and right and an interrupter for Lava Gout.",
        },
        general = {
            "Cleave Armor: reduces the tank's armor by 20% per stack up to 5 stacks. Divine Shield / Hand of Protection can remove the stacks; otherwise an off-tank taunts.",
            "Intimidating Roar: a fear effect that pins nearby players in place for 4 seconds rather than scattering them - Tremor Totem or Fear Ward can prevent/break it; otherwise just have healing ready.",
            "Summon Flamecaller: waves of Onyx Flamecallers enter from the left and right sides throughout the fight and need to be picked up by a tank on each side. Blast Nova hits everyone within 40 yards; Lava Gout hits a single target and can be interrupted.",
        },
        tank = {
            "Two tanks taunt-swap on Cleave Armor (each stack -20% armor).",
            "Onyx Flamecallers come every 40 seconds#{ from one side/ from both sides}: an off-tank picks them up and drags them to the boss for cleave.",
            "Intimidating Roar (every 30 seconds) fears everyone nearby - Fear Ward/Tremor Totem on tanks.",
        },
        heal = {
            "Flamecallers' Blast Nova hits the raid; Lava Gout is a single-target fire hit (interrupt it).",
            "Tank damage climbs with Cleave Armor stacks - watch the swap.",
            "After each Roar, top off anyone hit while feared.",
        },
        dps = {
            "Kill the Flamecallers first (interrupt Lava Gout and Blast Nova), then Zarithrian.",
            "Don't stand in front of him.",
            "Melee stay behind; ranged spread.",
        },
        abilities = {
            { kind = "debuff", id = 74367, name = "Cleave Armor", desc = "Reduces a tank's armor by 20% per stack (up to 5)." },
            { kind = "debuff", id = 74384, name = "Intimidating Roar", desc = "Fears nearby players in place for 4 seconds. Tremor Totem/Fear Ward can stop it." },
            { id = 74398, name = "Summon Flamecaller", desc = "Summons Onyx Flamecallers from the sides in waves through the fight." },
            { id = 74392, name = "Blast Nova", desc = "The Flamecallers' AoE within 40 yards. Interrupt/kill them quickly." },
            { id = 74394, name = "Lava Gout", desc = "The Flamecallers' single-target hit. Interrupt it." },
        },
        hard = {
            "Heroic: adds hit harder and Cleave Armor is more punishing - taunt-swap earlier and keep interrupts perfect.",
        },
    },
    {
        name = "Halion",
        aliases = { "Twilight Halion", "Living Inferno", "Living Ember" },
        tldr = "P1 (Physical Realm): stack on one side, run through the boss when Meteor Strike is marked, and run out to the edge with Fiery Combustion. P2 (75%): enter the Twilight Realm, avoid Twilight Cutter. P3 (50%): split into two teams and keep both boss health bars even (Corporeality).",
        start = {
            "Two tanks - one in the Physical Realm, one in the Twilight Realm. Bring at least two players who can Dispel Magic or Remove Curse (for Fiery Combustion and Soul Consumption).",
            "Bring 5-7 healers, with mobile healers (Priests, Druids) for the Twilight Realm. Paladin Shadow/Fire Resistance Auras help.",
            "Buff your two teams: melee-heavy Twilight team wants Abomination's Might / Trueshot Aura, Faerie Fire/Misery, Sunder/Expose Armor and Icy Talons/Windfury. Caster Physical team wants Demonic Pact, Wrath of Air, Moonkin Aura/Elemental Oath.",
        },
        general = {
            "## Phase 1: Physical Realm",
            "A few seconds after the pull, a ring of flames closes around the arena - everyone must move in TOGETHER. Tank Halion in the center with the raid loosely stacked on her side (never in front or behind).",
            "Cleave, Flame Breath and Tail Lash: only the tank stands in front; never stand behind.",
            "Fiery Combustion: a stacking debuff on a random player. They must run to the nearest EDGE of the room quickly and be dispelled - it leaves a fiery void zone whose size depends on how long it took. When it ends it knocks nearby players back. Save movement abilities (Nitro Boosts, Blink) for this.",
            "Meteor Strike: a random player is marked and after 5 seconds it explodes in a wide radius and fires a 4-way cross of flames. The whole raid moves THROUGH the boss to the opposite side before it lands. If the tank is marked, the tank runs through the dragon, spinning her.",
            "## Phase 2: Twilight Realm (75% health)",
            "Halion vanishes from the Physical Realm and opens a portal to the Twilight Realm. The TANK enters first (big defensive cooldown), then healers and the rest of the raid.",
            "Fiery Combustion is replaced by Soul Consumption, which behaves the same way but PULLS players into the void zone.",
            "Twilight Cutter: two orbs (four on heroic) rotate around the room, and every 30 seconds a lethal beam between them kills anything it touches. Stay on one side of Halion, moving consistently with the tank; don't spin too fast or too slow.",
            "Dusk Shroud: constant unavoidable shadow damage in the Twilight Realm every 2 seconds. Dark Breath: only the tank stands in front.",
            "## Phase 3 (50% health, both realms)",
            "Halion is active in BOTH realms at once. Split the raid into two roughly equal teams. Melee lean toward the Twilight Realm (less affected by the constant Cutter movement).",
            "Keep Halion's health in both realms as even as possible: Corporeality rises or falls with the difference. The higher the stacks, the LESS damage she takes and the MORE damage she deals. Coordinate percentages, call DPS stops, and swap players between realms if one side is ahead.",
        },
        tank = {
            "Phase 1: Physical-realm tank faces Halion away from the raid; nobody else in front or behind.",
            "Phase 2 (75%): Twilight tank enters the portal first and picks up Twilight Halion before the raid follows.",
            "Phase 3 (50%): one tank per realm; keep her still so both teams can control Corporeality.",
        },
        heal = {
            "Fiery Combustion (Physical, every 25 seconds) and Soul Consumption (Twilight) DoTs - dispel quickly once the target is at the edge.",
            "Meteor Strike (every 40 seconds) - heal those who didn't move out in time.",
            "Twilight Realm: Dusk Shroud ticks on everyone every 2 seconds; mobile healers are best there.",
        },
        dps = {
            "Phase 1: move through the boss to the far side when Meteor Strike is marked; with Fiery Combustion run to the edge before dispel.",
            "Phase 2: stay on one side of Halion, move with the raid as the Twilight Cutter rotates (every 30 seconds).",
            "Phase 3: watch Corporeality and stop/start DPS on the realm leader's call so both realms stay even.",
            "Berserk at 8 minutes.",
        },
        abilities = {
            { id = 845, name = "Cleave", desc = "Hits players in front of her. Only the tank is in front." },
            { id = 8873, name = "Flame Breath", desc = "Physical Realm frontal breath." },
            { id = 56910, name = "Tail Lash", desc = "Damages and stuns players behind her." },
            { kind = "debuff", id = 74562, name = "Fiery Combustion", desc = "A debuff you must run to the room edge with and have dispelled." },
            { id = 75879, name = "Meteor Strike", desc = "A marked player explodes in 5 seconds. The raid moves to the far side of Halion." },
            { id = 74806, name = "Dark Breath", desc = "Twilight Realm frontal breath." },
            { kind = "debuff", id = 75476, name = "Dusk Shroud", desc = "Constant shadow damage in the Twilight Realm." },
            { id = 74769, name = "Twilight Cutter", desc = "A lethal beam between orbs every 30 seconds. Don't touch it." },
            { kind = "debuff", id = 74792, name = "Soul Consumption", desc = "The Twilight version of Fiery Combustion: pulls players into the void zone." },
            { id = 74829, name = "Corporeality", desc = "Balances damage between realms. Keep both health bars even." },
        },
        hard = {
            "Heroic phase 1: each Meteor Strike spawns a Living Inferno and several Living Embers. Pick them up (Misdirection/Tricks of the Trade onto a tank) and cleave them down.",
            "Heroic Twilight Realm: there are 4 cutters instead of 2, forming a cross whenever Twilight Cutter is cast. This narrows the safe space and makes it much harder to get in and out with Soul Consumption.",
            "Heroic: Soul Consumption continually reapplies its slow, so you need Dispel Magic or Hand of Freedom. Drop your Soul Consumption at the edge of the cutter that is moving AWAY from you so you have time to escape the next one.",
            "The hardest change: the void zones from Fiery Combustion and Soul Consumption appear in and affect BOTH realms in heroic. The teams must coordinate where to drop void zones so they don't limit the other team's movement.",
        },
    },
}, "AzerothCore boss scripts (timers, counts), Icy Veins and Warcraft Tavern guides")
