-- The Obsidian Sanctum and The Eye of Eternity
local WM = WrathMentor

WM:AddRaid("os", "The Obsidian Sanctum", { "The Obsidian Sanctum" }, {
    {
        name = "Sartharion",
        aliases = { "Tenebron", "Shadron", "Vesperon" },
        tldr = "Dodge the lava walls (Flame Tsunami, every 25 seconds) and Lava Strike fire, keep Sartharion facing away, and kill each drake you left alive as it arrives. Leaving 1, 2 or 3 drakes alive (1D/2D/3D) is the hard mode.",
        start = {
            "Decide how many drakes (Tenebron, Shadron, Vesperon) to leave alive BEFORE the pull - each one is a hard mode. Kill the ones you don't want on their patrol first.",
            "Main tank takes Sartharion in the middle area and faces him away from the raid. Nobody stands in front (Flame Breath) or behind (Tail Lash).",
            "Off-tank: picks up Lava Blazes and, if drakes are alive, each drake as it lands.",
            "Berserk at 15 minutes.",
        },
        general = {
            "## Sartharion (always)",
            "Flame Tsunami (every 25 seconds): walls of lava cross the room from one side. Run through the gap to the safe side - the raid leader calls the side. Adds touched by the lava get a big buff.",
            "Lava Strike: Fire Cyclones hit the ground and spawn Lava Blazes. The off-tank collects them and DPS kill them.",
            "Cleave and Flame Breath in front, Tail Lash behind.",
            "At 30% he Berserks (faster, harder hits): tank cooldowns. At 10% the Fire Cyclones start raining Lava Strikes every 1-2 seconds - burn him fast or stack on him and AoE the Blazes.",
            "## Drakes (only if left alive)",
            "Tenebron joins about 20 seconds in, Shadron at 1 minute, Vesperon at 2 minutes. Each one lands, gets tanked, and should die before the next arrives.",
            "Tenebron: opens a Twilight Portal and lays eggs inside it. If the eggs aren't killed within about 25 seconds, Twilight Whelps hatch into the normal realm and shred armor (Fade Armor) - kill them.",
            "Shadron: while Shadron or his Acolyte (inside the portal) is alive, Sartharion is immune to damage and deals more fire damage (Gift of Twilight). Kill the Acolyte in the portal or kill Shadron quickly.",
            "Vesperon: his Acolyte puts Twilight Torment on the whole raid (more shadow damage taken, damage when you attack). Send a group into the portal to kill the Acolyte immediately.",
            "Drakes cast Shadow Breath (cone) and Shadow Fissure (void zone, move out).",
            "Each drake killed while Sartharion is alive gives him Twilight Revenge (faster, harder hits).",
        },
        tank = {
            "Main tank: face Sartharion away from the raid, move with the raid through each Flame Tsunami gap, and use cooldowns at 30% (Berserk) and when drake buffs stack.",
            "Off-tank: collect Lava Blazes and keep them out of the lava waves. With drakes alive, pick up each drake where it lands and face it away from the raid (Shadow Breath).",
            "3D: Vesperon + Torment + Sartharion's breaths can kill a tank fast - plan your cooldowns for the moment Vesperon lands.",
        },
        heal = {
            "Stay central so a Flame Tsunami never separates you from the tanks; always run to the safe side with the raid.",
            "Heal through Flame Tsunami damage (it also leaves a DoT).",
            "With drakes: tanks take big Shadow Breaths; with Vesperon alive the raid takes extra shadow damage until his Acolyte dies.",
        },
        dps = {
            "Kill Lava Blazes quickly, then Sartharion. Never pull Blazes through the lava.",
            "With drakes: switch to each drake as it lands. Assigned DPS jump into the Twilight Portal for eggs (Tenebron) or Acolytes (Shadron, Vesperon).",
            "Move out of Shadow Fissures and through the Tsunami gap.",
        },
        abilities = {
            { ids = { 56909 }, name = "Cleave", desc = "Hits players in front of him. Only the tank stands there." },
            { ids = { 56908, 58956 }, name = "Flame Breath", desc = "Massive fire damage in a cone in front of him." },
            { ids = { 56910, 58957 }, name = "Tail Lash", desc = "Damages and knocks back players behind him. Don't stand there." },
            { id = 57491, name = "Flame Tsunami", desc = "A wall of lava that runs across the room. Get out of its path." },
            { id = 57581, name = "Void Blast", desc = "A void zone under a player. Run out of it." },
            { kind = "buff", id = 61254, name = "Will of Sartharion", desc = "With drakes alive, Sartharion and the drakes have increased health." },
            { ids = { 57570, 59126 }, name = "Shadow Breath", desc = "The drakes' shadow breath. Tanks face them away from the raid." },
            { kind = "buff", ids = { 57835, 58766 }, name = "Gift of Twilight", desc = "While Shadron or his Acolyte lives, Sartharion is immune to damage and deals more fire damage." },
            { kind = "debuff", ids = { 57935, 58853 }, name = "Twilight Torment", desc = "While Vesperon's Acolyte lives: more shadow damage taken and shadow damage to yourself when you attack." },
            { kind = "debuff", id = 60708, name = "Fade Armor", desc = "Twilight Whelps reduce a tank's armor. Kill them fast." },
        },
        hard = {
            "The hard mode is chosen by which drakes are alive when you pull: 0 (normal), 1D, 2D, or 3D. Each drake is its own mini-boss that joins mid-fight.",
            "Every drake left alive makes Sartharion and the drakes tougher (Will of Sartharion adds health) and adds one extra mechanic: Tenebron = Twilight Whelps, Shadron = Gift of Twilight (Sartharion immune + 50% fire damage while his Acolyte/Shadron lives), Vesperon = Twilight Torment.",
            "Arrival times: Tenebron about 20 seconds, Shadron at 1 minute, Vesperon at 2 minutes. Kill each drake before the next one arrives.",
            "Reward: each drake left alive adds extra loot, and all 3 drakes gives the bonus items and the Twilight/Black Drake mount (10-man Reins of the Black Drake, 25-man Reins of the Twilight Drake).",
            "3D is the danger point: Vesperon plus Torment can one-shot the tank. Save all raid and tank cooldowns for that moment and kill the Acolyte immediately.",
        },
    },
}, "AzerothCore boss script (timers), Icy Veins and Warcraft Tavern guides")

WM:AddRaid("eoe", "The Eye of Eternity", { "The Eye of Eternity" }, {
    {
        name = "Malygos",
        aliases = { "Nexus Lord", "Scion of Eternity" },
        tldr = "P1: face him away, run from his face after every Vortex, kill Power Sparks before they reach him. P2: kill #{2/4} Nexus Lords and #{4/8} Scions, stand in Arcane Overload bubbles for Deep Breath. P3: on drakes - spam 1-1-2 (healers 3/4), avoid Static Field, Flame Shield before Surge of Power.",
        start = {
            "Tank Malygos facing away from the raid (Arcane Breath is a frontal cone).",
            "Ranged stand loosely spread behind/beside him. Assign 1-2 players to Power Sparks.",
            "Decide Phase 3 roles now: #{2/4-5} players heal with their drakes, everyone else DPS. Berserk at 10 minutes.",
        },
        general = {
            "## Phase 1 (100% to 50%)",
            "Arcane Storm hits #{5/12} random players every 10-15 seconds.",
            "Vortex: 30 seconds in, then every minute. Everyone is lifted and spun for about 10 seconds taking damage (instant casts still work). When you're dropped, run AWAY from his face so Arcane Breath can't hit you.",
            "Power Sparks come out of the portals every 20-30 seconds and float to Malygos. If one reaches him he gets +50% damage. Kill them on the way (they can be slowed/stunned). A killed Spark leaves a pool that buffs the damage of players standing in it.",
            "## Phase 2 (at 50%)",
            "Malygos flies above the platform and can't be attacked. #{2/4} Nexus Lords (melee, tanked) and #{4/8} Scions of Eternity (flying on discs, cast Arcane Barrage) arrive.",
            "About once a minute he casts Deep Breath: massive arcane damage to everyone NOT inside an Arcane Overload bubble. He drops a new bubble every 15 seconds; bubbles shrink as they absorb damage, so move to a fresh one.",
            "Discs dropped by dead Nexus Lords/Scions can be mounted to reach the flying Scions.",
            "Phase 3 starts as soon as every Nexus Lord and Scion is dead.",
            "## Phase 3 (drakes)",
            "The platform breaks; everyone rides a red drake. There's no tanking.",
            "DPS: Flame Spike (1) builds combo points, Engulf in Flames (2) spends them for a stacking DoT. Rotation: 1-1-2, refresh 2 before it drops.",
            "Healers: Revivify (3) is a stacking HoT, Life Burst (4) is a big AoE heal that uses combo points. Stay stacked with the raid.",
            "Arcane Pulse hits anyone within 30 yards of Malygos - keep 30+ yards away.",
            "Static Field (every 12 seconds): a 30-yard sphere of heavy damage. Fly out with the raid (Blazing Speed, 6, helps).",
            "Surge of Power (every few seconds) targets a drake - use Flame Shield (5) when you're targeted.",
        },
        tank = {
            "Phase 1: face Malygos away; reposition quickly after each Vortex drops you.",
            "Phase 2: pick up the Nexus Lords and keep them inside an Arcane Overload bubble before each Deep Breath.",
            "Phase 3: you're a drake DPS or healer like everyone else.",
        },
        heal = {
            "Phase 1: heal through Arcane Storm and Vortex (instants work while spinning).",
            "Phase 2: stand in Arcane Overload bubbles and heal the Arcane Barrage targets.",
            "Phase 3 healers: keep Revivify stacks rolling on the group and use Life Burst on 5 combo points. Stay with the raid, 30+ yards from Malygos.",
        },
        dps = {
            "Phase 1: Power Sparks first (before they reach him), Malygos second. Stand in a killed Spark's pool for the damage buff.",
            "Phase 2: kill Nexus Lords on the ground; ranged and disc riders kill the Scions. Bubble before every Deep Breath.",
            "Phase 3: 1-1-2 rotation, keep Engulf in Flames up, Flame Shield on Surge of Power, follow the raid out of Static Field.",
        },
        abilities = {
            { id = 56105, name = "Vortex", desc = "30 seconds in, then every minute: the raid is lifted and spun for about 10 seconds of damage. Run away from his face when you land." },
            { ids = { 56272, 60072 }, name = "Arcane Breath", desc = "A cone of arcane damage in front of him. Only the tank stands there." },
            { kind = "buff", id = 56152, name = "Power Spark", desc = "A spark that boosts Malygos' damage by 50% if it reaches him. Kill it first." },
            { id = 56505, spellName = "Surge of Power", name = "Deep Breath", desc = "Massive arcane damage to everyone not on a disc during phase 2." },
            { id = 56438, name = "Arcane Overload", desc = "Pink zones that reduce magic damage taken by 50%. Shrink over time." },
            { ids = { 56397, 63934 }, name = "Arcane Barrage", desc = "Phase 2: Scions of Eternity cast this on random players." },
            { id = 57432, name = "Arcane Pulse", desc = "Damage to anyone within 30 yards of Malygos in phase 3." },
            { id = 57430, name = "Static Field", desc = "Phase 3, every 12 seconds: a 30-yard sphere of heavy damage. Fly out with the raid." },
            { ids = { 56548, 57407 }, name = "Surge of Power", desc = "A beam on a random drake. Flame Shield helps." },
            { id = 56091, name = "Flame Spike", desc = "Drake ability 1: hits Malygos and builds combo points." },
            { kind = "debuff", id = 56092, name = "Engulf in Flames", desc = "Drake ability 2: spends combo points and stacks a damage effect on Malygos." },
            { id = 57090, name = "Revivify", desc = "Drake ability 3: a stacking heal over time." },
            { id = 57143, name = "Life Burst", desc = "Drake ability 4: big AoE heal that uses combo points." },
            { kind = "buff", id = 57108, name = "Flame Shield", desc = "Drake ability 5: damage reduction - use it when Surge of Power targets you." },
            { kind = "buff", id = 57092, name = "Blazing Speed", desc = "Drake ability 6: speed boost to get out of Static Field." },
        },
    },
}, "AzerothCore boss script (timers, add counts), Icy Veins and Warcraft Tavern guides")
